// Databricks notebook source
// MAGIC %md
// MAGIC # AI-Assisted Pull Requests Monitor
// MAGIC
// MAGIC **Context**: This notebook supports **monthly OKR reporting** for pull requests created with AI assistance in the `itaipu` (Rapidash / Warp Pipe) and `cross-segment-ai-tools` repositories.
// MAGIC
// MAGIC **Objective**: Quantify merged AI-assisted PR volume, authors, timing, estimated outputs, and structured fields from descriptions for leadership reporting.
// MAGIC
// MAGIC **Method**:
// MAGIC 1. Read merged PR events from the canonical Ist dataset and apply repository-specific AI signatures.
// MAGIC 2. Classify each PR by `ai_tool` (Rapidash, Warp Pipe, or cross-segment-ai-tools).
// MAGIC 3. Build monthly aggregates, author breakdowns, time-to-merge metrics, PR listings, estimated output counts, cumulative totals, and content extractions.
// MAGIC 4. Materialize results to Delta tables under `usr.br__customer_lifecycle_optimization`.
// MAGIC 5. Run sanity checks (no joins in this pipeline; validate filters, columns, grain, and aggregation consistency).
// MAGIC
// MAGIC **Analysis structure**:
// MAGIC - 1. Imports
// MAGIC - 2. Data sources
// MAGIC - 3. Widgets
// MAGIC - 4. Variable filters
// MAGIC - 5. Functions
// MAGIC - 6. Code / analysis
// MAGIC - 7. Validation
// MAGIC - 8. Display
// MAGIC
// MAGIC **Data sources**:
// MAGIC - `etl.ist__dataset.pull_request_events` — single base table for merged PR events (closed, merged), filters, and text fields used for AI detection and output estimation.
// MAGIC
// MAGIC **Main assumptions**:
// MAGIC - `action === "closed"` and `is_merged === true` define the merged-PR population; `merged_at >= 2025-01-01` bounds the OKR window.
// MAGIC - Rapidash PRs are identified by `repo_name === "itaipu"` and `description` containing `Generated by Rapidash`.
// MAGIC - Warp Pipe PRs use the same repo plus title/description patterns documented in the filter block (excludes infra-only mentions).
// MAGIC - All PRs in `cross-segment-ai-tools` are treated as AI-assisted with tool label `cross-segment-ai-tools`.
// MAGIC - Estimated output counts for Rapidash use description parsing heuristics; they are approximate, not ground truth.

// COMMAND ----------

// MAGIC %md
// MAGIC ## 1. Imports

// COMMAND ----------

// DBTITLE 1,Spark SQL imports
import org.apache.spark.sql.functions._

// COMMAND ----------

// MAGIC %md
// MAGIC ## 2. Data sources

// COMMAND ----------

// DBTITLE 1,Load pull request events base
// Base dataset: one row per PR event; analysis restricts to merged closes only.
val pullRequestEventsTableName = "etl.ist__dataset.pull_request_events"
val pullRequestEvents = spark.table(pullRequestEventsTableName)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 3. Widgets

// COMMAND ----------

// MAGIC %md
// MAGIC No runtime widgets. Scope is fixed for this pipeline (`merged_at` from 2025-01-01 onward per OKR definition).

// COMMAND ----------

// MAGIC %md
// MAGIC ## 4. Variable filters

// COMMAND ----------

// DBTITLE 1,Define analysis scope constants
val mergedPullRequestsStartDate = "2025-01-01"

val mergedPullRequestEvents = pullRequestEvents
  .filter(col("action") === "closed")
  .filter(col("is_merged") === true)
  .filter(col("merged_at") >= mergedPullRequestsStartDate)

// Rapidash: explicit signature "Generated by Rapidash" in the description
val rapidashItaipuFilter =
  col("repo_name") === "itaipu" &&
  col("description").like("%Generated by Rapidash%")

// Warp Pipe: PRs that effectively create products (JM + Activity + Eligibility + Conversion).
// Excludes infra/cleanup PRs that only mention Warp Pipe.
val warpPipeItaipuFilter =
  col("repo_name") === "itaipu" && (
    col("description").like("%Warp Pipe%") ||
    col("description").like("%WarpPipe%")
  ) && (
    col("title").like("%w/ Warp Pipe%") ||
    col("description").like("%Config object%") ||
    col("description").like("%productCustomerStatus%")
  )

val aiAssistedPullRequests = mergedPullRequestEvents
  .filter(rapidashItaipuFilter || warpPipeItaipuFilter || col("repo_name") === "cross-segment-ai-tools")
  .withColumn(
    "ai_tool",
    when(col("repo_name") === "cross-segment-ai-tools", lit("cross-segment-ai-tools"))
      .when(col("description").like("%Generated by Rapidash%"), lit("Rapidash"))
      .otherwise(lit("Warp Pipe"))
  )

// COMMAND ----------

// MAGIC %md
// MAGIC ## 5. Functions

// COMMAND ----------

// MAGIC %md
// MAGIC No shared helper functions; transformation logic stays in the analysis section so filter criteria remain visible next to metrics.

// COMMAND ----------

// MAGIC %md
// MAGIC ## 6. Code / analysis

// COMMAND ----------

// DBTITLE 1,Estimated outputs per PR from description heuristics
// Counting methodology (unchanged):
// - New Rapidash PRs: occurrences of `**Type**:` in the description
// - Update/migration PRs: bullets matching `- **PascalCaseName**`
// - Fallback: max(1, changed_files - 2)
// - cross-segment-ai-tools and Warp Pipe: 1 output per PR
val typeDeclarationCount = size(split(col("description"), "\\*\\*Type\\*\\*:")) - 1

val attributeBulletCount =
  size(expr("filter(split(description, '\n'), x -> x rlike '^- \\\\*\\\\*[A-Z][a-zA-Z0-9]*\\\\*\\\\*')"))

val attributeCountEstimate = greatest(typeDeclarationCount, attributeBulletCount)

val pullRequestsWithEstimatedOutputs = aiAssistedPullRequests
  .withColumn(
    "estimated_outputs",
    when(col("ai_tool") === "cross-segment-ai-tools", lit(1))
      .when(col("ai_tool") === "Warp Pipe", lit(1))
      .when(attributeCountEstimate > 0, attributeCountEstimate)
      .otherwise(greatest(lit(1), col("changed_files") - 2))
  )

// COMMAND ----------

// DBTITLE 1,Monthly PR volume and persist
val monthlyVolume = pullRequestsWithEstimatedOutputs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    countDistinct("author").alias("unique_authors"),
    sum("added_lines").alias("total_lines_added"),
    sum("deleted_lines").alias("total_lines_deleted"),
    sum("changed_files").alias("total_files_changed")
  )
  .orderBy(col("month").desc, col("ai_tool"))

monthlyVolume.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_volume_mensal"
)

// COMMAND ----------

// DBTITLE 1,Breakdown by author and month and persist
val monthlyVolumeByAuthor = pullRequestsWithEstimatedOutputs
  .groupBy(
    date_trunc("month", col("merged_at")).alias("month"),
    col("ai_tool"),
    col("author")
  )
  .agg(
    countDistinct("pr_number").alias("prs_merged"),
    sum("added_lines").alias("lines_added"),
    sum("deleted_lines").alias("lines_deleted")
  )
  .orderBy(col("month").desc, col("prs_merged").desc)

monthlyVolumeByAuthor.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_por_autor"
)

// COMMAND ----------

// DBTITLE 1,Average time to merge and persist
val monthlyTimeToMerge = pullRequestsWithEstimatedOutputs
  .withColumn(
    "hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 1)
  )
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    round(avg("hours_to_merge"), 1).alias("avg_hours_to_merge"),
    min("hours_to_merge").alias("min_hours"),
    max("hours_to_merge").alias("max_hours"),
    countDistinct("pr_number").alias("total_prs")
  )
  .orderBy(col("month").desc, col("ai_tool"))

monthlyTimeToMerge.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_tempo_merge"
)

// COMMAND ----------

// DBTITLE 1,Individual PR list and persist
val pullRequestDetailList = pullRequestsWithEstimatedOutputs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .withColumn(
    "hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 0)
  )
  .select(
    col("month"),
    col("ai_tool"),
    col("repo_name"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("added_lines"),
    col("deleted_lines"),
    col("changed_files"),
    col("hours_to_merge"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

pullRequestDetailList.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_lista_prs"
)

// COMMAND ----------

// DBTITLE 1,Estimated outputs per PR table and persist
val outputsPerPullRequest = pullRequestsWithEstimatedOutputs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

outputsPerPullRequest.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_outputs_por_pr"
)

// COMMAND ----------

// DBTITLE 1,Total AI outputs per month compute and optional persist
val monthlyOutputTotals = pullRequestsWithEstimatedOutputs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    sum("estimated_outputs").alias("total_outputs"),
    round(avg("estimated_outputs"), 1).alias("avg_outputs_per_pr"),
    countDistinct("author").alias("unique_authors")
  )
  .orderBy(col("month").desc)

// monthlyOutputs.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_mensais")

// COMMAND ----------

// DBTITLE 1,Cumulative outputs and persist
val cumulativeOutputTotals = pullRequestsWithEstimatedOutputs
  .agg(
    sum("estimated_outputs").alias("total_outputs_to_date"),
    countDistinct("pr_number").alias("total_prs_to_date"),
    countDistinct("author").alias("unique_authors_to_date")
  )

cumulativeOutputTotals.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_total_acumulado"
)

// COMMAND ----------

// DBTITLE 1,PR content breakdown from description and persist
val pullRequestContentBreakdown = pullRequestsWithEstimatedOutputs
  .withColumn("attribute_type",
    regexp_extract(col("description"), "\\*\\*Type\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("owner_squad",
    regexp_extract(col("description"), "\\*\\*Owner\\*\\*:\\s*(?:Squad\\.)?([^\\n]+)", 1))
  .withColumn("domain",
    regexp_extract(col("description"), "\\*\\*Domain\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("context_summary",
    regexp_extract(col("description"), "###\\s*Context\\n+([^#\\n][^\\n]{0,200})", 1))
  .withColumn("output_description",
    regexp_extract(col("description"), "\\*\\*Output[:\\*]*\\s*([^\\n]{0,200})", 1))
  .withColumn("warp_pipe_product",
    regexp_extract(col("title"), "(?i)Add\\s+(.+?)\\s+(?:Activity|JM|Journey)", 1))
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("attribute_type"),
    col("owner_squad"),
    col("domain"),
    col("context_summary"),
    col("output_description"),
    col("warp_pipe_product"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

pullRequestContentBreakdown.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_pr_content"
)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 7. Validation

// COMMAND ----------

// MAGIC %md
// MAGIC **Joins**: This notebook uses **no joins** — all metrics are derived from `etl.ist__dataset.pull_request_events` only. Validations below cover filter impact, required columns, duplicate risk at PR grain, and aggregation safety.

// COMMAND ----------

// DBTITLE 1,Check required columns on filtered base
val requiredColumnsForPipeline = Seq(
  "action",
  "is_merged",
  "merged_at",
  "created_at",
  "repo_name",
  "description",
  "title",
  "pr_number",
  "author",
  "added_lines",
  "deleted_lines",
  "changed_files"
)

val missingColumns = requiredColumnsForPipeline.filterNot(mergedPullRequestEvents.columns.contains)
require(missingColumns.isEmpty, s"Missing required columns after merged-pr filter: ${missingColumns.mkString(", ")}")

// COMMAND ----------

// DBTITLE 1,Validate filter impact and merged_at bounds
val mergedClosedRowCount = mergedPullRequestEvents.count()
val aiAssistedRowCount = aiAssistedPullRequests.count()

println(s"Rows after merged + date filter: $mergedClosedRowCount")
println(s"Rows after AI repo/signature filter: $aiAssistedRowCount")

val mergedAtMinMax = mergedPullRequestEvents.agg(min("merged_at").alias("min_merged_at"), max("merged_at").alias("max_merged_at")).head()
println(s"merged_at min (merged scope): ${mergedAtMinMax.getAs[Any]("min_merged_at")}")
println(s"merged_at max (merged scope): ${mergedAtMinMax.getAs[Any]("max_merged_at")}")

val nullMergedAtInScope = mergedPullRequestEvents.filter(col("merged_at").isNull).count()
require(nullMergedAtInScope == 0, s"Unexpected null merged_at in merged scope: $nullMergedAtInScope rows")

// COMMAND ----------

// DBTITLE 1,Check duplicate grain repo_name and pr_number in AI slice
val duplicatePrKeys = aiAssistedPullRequests
  .groupBy("repo_name", "pr_number")
  .count()
  .filter(col("count") > 1)

val duplicatePrKeyCount = duplicatePrKeys.count()
println(s"Duplicate (repo_name, pr_number) groups in AI slice: $duplicatePrKeyCount")
if (duplicatePrKeyCount > 0) {
  display(duplicatePrKeys.limit(100))
}

// COMMAND ----------

// DBTITLE 1,Validate aggregation safety for monthly PR counts
val distinctPrInAiSlice = aiAssistedPullRequests.select("pr_number").distinct().count()
val sumMonthlyPrsAcrossTools = monthlyVolume.agg(sum("total_prs").alias("sum_distinct_prs")).head().getLong(0)

println(s"Global distinct pr_number in AI slice: $distinctPrInAiSlice")
println(s"Sum of monthly total_prs (all month x ai_tool rows): $sumMonthlyPrsAcrossTools")

require(
  distinctPrInAiSlice == sumMonthlyPrsAcrossTools,
  "Monthly volume total_prs summed across rows should match global distinct pr_number count (each PR falls in exactly one month and one ai_tool)."
)

val sumPrsMergedAcrossAuthorRows = monthlyVolumeByAuthor.agg(sum("prs_merged").alias("s")).head().getLong(0)
println(
  s"Sum of prs_merged across author breakdown rows: $sumPrsMergedAcrossAuthorRows (can exceed global distinct PRs if co-authorship or duplicate keys exist in source)"
)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 8. Display

// COMMAND ----------

// DBTITLE 1,Display monthly volume
display(monthlyVolume)

// COMMAND ----------

// DBTITLE 1,Display monthly volume by author
display(monthlyVolumeByAuthor)

// COMMAND ----------

// DBTITLE 1,Display time to merge metrics
display(monthlyTimeToMerge)

// COMMAND ----------

// DBTITLE 1,Display PR detail list
display(pullRequestDetailList)

// COMMAND ----------

// DBTITLE 1,Display outputs per PR
display(outputsPerPullRequest)

// COMMAND ----------

// DBTITLE 1,Display monthly output totals
display(monthlyOutputTotals)

// COMMAND ----------

// DBTITLE 1,Display cumulative totals
display(cumulativeOutputTotals)

// COMMAND ----------

// DBTITLE 1,Display PR content breakdown
display(pullRequestContentBreakdown)
