// Databricks notebook source
// MAGIC %md
// MAGIC # AI-Assisted PRs Monitor (Itaipu & cross-segment)
// MAGIC
// MAGIC **Context**: This notebook supports **monthly OKR reporting** on pull requests that were created or delivered with AI assistance, focusing on the `itaipu` repository (Rapidash / Warp Pipe patterns) and the `cross-segment-ai-tools` repository (tooling and templates).
// MAGIC
// MAGIC **Objective**: Measure merged AI-assisted PR volume, authors, line churn, time-to-merge, estimated outputs, and structured fields extracted from descriptions, then materialize curated tables for reporting.
// MAGIC
// MAGIC **Method**:
// MAGIC 1. Read merged, closed PR events from `etl.ist__dataset.pull_request_events` within a configurable merge-date floor.
// MAGIC 2. Classify PRs into `ai_tool` buckets (Rapidash, Warp Pipe, cross-segment-ai-tools) using the same filters as the legacy notebook.
// MAGIC 3. Build monthly and PR-level metrics, including estimated AI outputs from description heuristics.
// MAGIC 4. Run validations for required columns, PR-grain duplicates, and aggregation safety before relying on sums at PR level.
// MAGIC 5. Write results to Delta tables under `usr.br__customer_lifecycle_optimization` and display key outputs.
// MAGIC
// MAGIC **Analysis structure**:
// MAGIC - 0. Intro / README (this block)
// MAGIC - 1. Imports
// MAGIC - 2. Data sources
// MAGIC - 3. Widgets
// MAGIC - 4. Variable filters
// MAGIC - 5. Functions
// MAGIC - 6. Code / analysis
// MAGIC - 7. Validation
// MAGIC - 8. Display
// MAGIC
// MAGIC **Data sources**:
// MAGIC - `etl.ist__dataset.pull_request_events` — single source for PR events, filters, and content fields used in metrics.
// MAGIC
// MAGIC **Main assumptions**:
// MAGIC - `action = closed` and `is_merged = true` define the merged PR population.
// MAGIC - PR identity is unique on `(repo_name, pr_number)`; duplicate rows at that grain would inflate sums that use `sum(...)` across PR-level attributes.
// MAGIC - Merge timestamps and string filters behave as in the original notebook (including `merged_at >= mergeStartDate` as a string comparison where applicable).

// COMMAND ----------

// MAGIC %md
// MAGIC ## 1. Imports

// COMMAND ----------

// DBTITLE 1,Imports
// MAGIC %run "/data-analysts/utils-uc"
import org.apache.spark.sql.Column
import org.apache.spark.sql.DataFrame
import org.apache.spark.sql.functions._

// COMMAND ----------

// MAGIC %md
// MAGIC ## 2. Data sources

// COMMAND ----------

// DBTITLE 1,Register pull request events source
val pullRequestEventsSource = "etl.ist__dataset.pull_request_events"
val pullRequestEvents = spark.table(pullRequestEventsSource)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 3. Widgets

// COMMAND ----------

// DBTITLE 1,Runtime parameters
dbutils.widgets.text("mergeStartDate", "2025-01-01")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 4. Variable filters

// COMMAND ----------

// DBTITLE 1,Apply merged closed PR scope
val mergeStartDate = dbutils.widgets.get("mergeStartDate")

val allPRs = pullRequestEvents
  .filter(col("action") === "closed")
  .filter(col("is_merged") === true)
  .filter(col("merged_at") >= mergeStartDate)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 5. Functions

// COMMAND ----------

// DBTITLE 1,AI tool classification filters
// Rapidash: explicit signature "Generated by Rapidash" in the description
def rapidashFilterCondition(): Column =
  col("repo_name") === "itaipu" &&
    col("description").like("%Generated by Rapidash%")

// Warp Pipe: PRs that effectively create products (JM + Activity + Eligibility + Conversion)
// Excludes infra/cleanup PRs that only mention Warp Pipe
def warpPipeFilterCondition(): Column =
  col("repo_name") === "itaipu" && (
    col("description").like("%Warp Pipe%") ||
      col("description").like("%WarpPipe%")
  ) && (
    col("title").like("%w/ Warp Pipe%") ||
      col("description").like("%Config object%") ||
      col("description").like("%productCustomerStatus%")
  )

def crossSegmentRepoCondition(): Column =
  col("repo_name") === "cross-segment-ai-tools"

// COMMAND ----------

// DBTITLE 1,Build AI-assisted PR dataframe
def buildAiAssistedPullRequests(base: DataFrame): DataFrame = {
  val rf = rapidashFilterCondition()
  val wf = warpPipeFilterCondition()
  val xf = crossSegmentRepoCondition()
  base
    .filter(rf || wf || xf)
    .withColumn(
      "ai_tool",
      when(col("repo_name") === "cross-segment-ai-tools", lit("cross-segment-ai-tools"))
        .when(col("description").like("%Generated by Rapidash%"), lit("Rapidash"))
        .otherwise(lit("Warp Pipe"))
    )
}

// COMMAND ----------

// MAGIC %md
// MAGIC ## 6. Code / analysis

// COMMAND ----------

// DBTITLE 1,Create AI-assisted PR population
val aiPRs = buildAiAssistedPullRequests(allPRs)

// COMMAND ----------

// DBTITLE 1,Prepare estimated outputs columns
val typeCount = size(split(col("description"), "\\*\\*Type\\*\\*:")) - 1

val bulletCount = size(expr("filter(split(description, '\n'), x -> x rlike '^- \\\\*\\\\*[A-Z][a-zA-Z0-9]*\\\\*\\\\*')"))

val attributeCount = greatest(typeCount, bulletCount)

val withOutputs = aiPRs
  .withColumn(
    "estimated_outputs",
    when(col("ai_tool") === "cross-segment-ai-tools", lit(1))
      .when(col("ai_tool") === "Warp Pipe", lit(1))
      .when(attributeCount > 0, attributeCount)
      .otherwise(greatest(lit(1), col("changed_files") - 2))
  )

// COMMAND ----------

// DBTITLE 1,Monthly PR volume and persist
val monthlyVolume = aiPRs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    countDistinct("author").alias("unique_authors"),
    sum("added_lines").alias("total_lines_added"),
    sum("deleted_lines").alias("total_lines_deleted"),
    sum("changed_files").alias("total_files_changed")
  )
  .orderBy(col("month").desc, col("ai_tool"))

monthlyVolume.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_volume_mensal")

// COMMAND ----------

// DBTITLE 1,Breakdown by author and persist
val byAuthor = aiPRs
  .groupBy(
    date_trunc("month", col("merged_at")).alias("month"),
    col("ai_tool"),
    col("author")
  )
  .agg(
    countDistinct("pr_number").alias("prs_merged"),
    sum("added_lines").alias("lines_added"),
    sum("deleted_lines").alias("lines_deleted")
  )
  .orderBy(col("month").desc, col("prs_merged").desc)

byAuthor.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_por_autor")

// COMMAND ----------

// DBTITLE 1,Average time to merge and persist
val timeToMerge = aiPRs
  .withColumn(
    "hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 1)
  )
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    round(avg("hours_to_merge"), 1).alias("avg_hours_to_merge"),
    min("hours_to_merge").alias("min_hours"),
    max("hours_to_merge").alias("max_hours"),
    countDistinct("pr_number").alias("total_prs")
  )
  .orderBy(col("month").desc, col("ai_tool"))

timeToMerge.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_tempo_merge")

// COMMAND ----------

// DBTITLE 1,Individual PR list and persist
val prList = aiPRs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .withColumn(
    "hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 0)
  )
  .select(
    col("month"),
    col("ai_tool"),
    col("repo_name"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("added_lines"),
    col("deleted_lines"),
    col("changed_files"),
    col("hours_to_merge"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

prList.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_lista_prs")

// COMMAND ----------

// DBTITLE 1,AI outputs per PR and persist
// Counting methodology (unchanged):
// - New Rapidash PRs: counts occurrences of `**Type**:` in the description
// - Update/migration PRs: counts attribute bullets matching `- **PascalCaseName**`
// - Fallback: changed_files as minimum estimate
// - cross-segment-ai-tools PRs: counted as 1 output per PR
val outputsPerPR = withOutputs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

outputsPerPR.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_por_pr")

// COMMAND ----------

// DBTITLE 1,Total AI outputs per month (display only; write left commented as in source)
val monthlyOutputs = withOutputs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    sum("estimated_outputs").alias("total_outputs"),
    round(avg("estimated_outputs"), 1).alias("avg_outputs_per_pr"),
    countDistinct("author").alias("unique_authors")
  )
  .orderBy(col("month").desc)

// monthlyOutputs.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_mensais")

// COMMAND ----------

// DBTITLE 1,Cumulative total of AI-generated outputs and persist
val cumulativeTotal = withOutputs
  .agg(
    sum("estimated_outputs").alias("total_outputs_to_date"),
    countDistinct("pr_number").alias("total_prs_to_date"),
    countDistinct("author").alias("unique_authors_to_date")
  )

cumulativeTotal.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_total_acumulado")

// COMMAND ----------

// DBTITLE 1,PR content breakdown and persist
val prContent = withOutputs
  .withColumn("attribute_type", regexp_extract(col("description"), "\\*\\*Type\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("owner_squad", regexp_extract(col("description"), "\\*\\*Owner\\*\\*:\\s*(?:Squad\\.)?([^\\n]+)", 1))
  .withColumn("domain", regexp_extract(col("description"), "\\*\\*Domain\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("context_summary", regexp_extract(col("description"), "###\\s*Context\\n+([^#\\n][^\\n]{0,200})", 1))
  .withColumn("output_description", regexp_extract(col("description"), "\\*\\*Output[:\\*]*\\s*([^\\n]{0,200})", 1))
  .withColumn("warp_pipe_product", regexp_extract(col("title"), "(?i)Add\\s+(.+?)\\s+(?:Activity|JM|Journey)", 1))
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("attribute_type"),
    col("owner_squad"),
    col("domain"),
    col("context_summary"),
    col("output_description"),
    col("warp_pipe_product"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

prContent.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_pr_content")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 7. Validation

// COMMAND ----------

// DBTITLE 1,Check required columns after scope filters
val requiredColumns = Seq(
  "action",
  "is_merged",
  "merged_at",
  "repo_name",
  "description",
  "title",
  "pr_number",
  "author",
  "added_lines",
  "deleted_lines",
  "changed_files",
  "created_at"
)

val missingColumns = requiredColumns.filterNot(allPRs.columns.contains)
require(
  missingColumns.isEmpty,
  s"Missing required columns on scoped PR events: ${missingColumns.mkString(", ")}"
)

// COMMAND ----------

// DBTITLE 1,Check duplicates at pull-request grain (repo_name pr_number)
val duplicatePrGrain = aiPRs
  .groupBy("repo_name", "pr_number")
  .count()
  .filter(col("count") > 1)

val duplicatePrGrainCount = duplicatePrGrain.count()
println(s"Duplicate (repo_name, pr_number) groups in aiPRs: $duplicatePrGrainCount")
display(duplicatePrGrain.orderBy(col("count").desc).limit(100))

// COMMAND ----------

// DBTITLE 1,Validate aggregation safety for PR-level sums
val totalAiRows = aiPRs.count()
val distinctPrKeys = aiPRs.select("repo_name", "pr_number").distinct().count()

println(s"aiPRs row count: $totalAiRows")
println(s"Distinct (repo_name, pr_number): $distinctPrKeys")

if (totalAiRows != distinctPrKeys) {
  println(
    "WARNING: Row count exceeds distinct PR keys. sum(added_lines), sum(deleted_lines), sum(changed_files), and sum(estimated_outputs) may double-count PR-level metrics unless each source row represents a distinct PR event you intend to sum."
  )
}

val sumAddedAllRows = aiPRs
  .agg(coalesce(sum("added_lines"), lit(0)).cast("long").alias("s"))
  .first()
  .getLong(0)

val sumAddedDedupedByPr = aiPRs
  .groupBy("repo_name", "pr_number")
  .agg(coalesce(max("added_lines"), lit(0)).cast("long").alias("added_lines_max"))
  .agg(coalesce(sum("added_lines_max"), lit(0L)).alias("s"))
  .first()
  .getLong(0)

println(s"Sum added_lines across all aiPRs rows: $sumAddedAllRows")
println(s"Sum of max(added_lines) per (repo_name, pr_number): $sumAddedDedupedByPr")

if (sumAddedAllRows != sumAddedDedupedByPr) {
  println(
    "WARNING: PR-grain deduped sum of added_lines differs from raw row sum. Review whether the event grain matches the intended OKR definition before interpreting line-churn totals."
  )
}

// COMMAND ----------

// MAGIC %md
// MAGIC ## 8. Display

// COMMAND ----------

// DBTITLE 1,Display monthly volume
display(monthlyVolume)

// COMMAND ----------

// DBTITLE 1,Display author breakdown
display(byAuthor)

// COMMAND ----------

// DBTITLE 1,Display time to merge
display(timeToMerge)

// COMMAND ----------

// DBTITLE 1,Display PR list
display(prList)

// COMMAND ----------

// DBTITLE 1,Display outputs per PR
display(outputsPerPR)

// COMMAND ----------

// DBTITLE 1,Display monthly outputs
display(monthlyOutputs)

// COMMAND ----------

// DBTITLE 1,Display cumulative totals
display(cumulativeTotal)

// COMMAND ----------

// DBTITLE 1,Display PR content breakdown
display(prContent)
