// Databricks notebook source
// MAGIC %md
// MAGIC # AI-Assisted PRs Monitor
// MAGIC
// MAGIC **Context**: Monitor merged pull requests that used AI-assisted workflows in the `itaipu` (Rapidash / Warp Pipe) and `cross-segment-ai-tools` repositories.
// MAGIC
// MAGIC **Objective**: Support **monthly OKR reporting** for AI-assisted PRs (volume, authors, time-to-merge, estimated outputs, and content fields extracted from descriptions).
// MAGIC
// MAGIC **Method**:
// MAGIC 1. Read closed, merged PR events from `etl.ist__dataset.pull_request_events` from a configurable merge-date cutoff.
// MAGIC 2. Classify PRs into `ai_tool` (Rapidash, Warp Pipe, cross-segment-ai-tools) using repository and description/title rules preserved from the original notebook.
// MAGIC 3. Build monthly and author-level aggregates, PR listings, estimated output counts, cumulative totals, and Rapidash/Warp Pipe content extracts.
// MAGIC 4. Materialize results to Delta tables under `usr.br__customer_lifecycle_optimization` and validate grain and schema assumptions.
// MAGIC
// MAGIC **Analysis structure**:
// MAGIC - 0. Intro / README (this block)
// MAGIC - 1. Imports
// MAGIC - 2. Data sources
// MAGIC - 3. Widgets
// MAGIC - 4. Variable filters
// MAGIC - 5. Functions
// MAGIC - 6. Code / analysis
// MAGIC - 7. Validation
// MAGIC - 8. Display
// MAGIC
// MAGIC **Data sources**:
// MAGIC - `etl.ist__dataset.pull_request_events` — closed, merged PR events; grain is one row per event; keys used: `repo_name`, `pr_number`, `author`, `merged_at`, `created_at`, description/title fields, line and file stats.
// MAGIC
// MAGIC **Assumptions / caveats**:
// MAGIC - Rapidash PRs are identified by `repo_name === "itaipu"` and `description` containing `Generated by Rapidash`.
// MAGIC - Warp Pipe PRs use additional title/description heuristics; infra-only mentions are excluded by design.
// MAGIC - `cross-segment-ai-tools` PRs are included in full and tagged as that tool.
// MAGIC - Estimated AI outputs use description parsing heuristics documented in the analysis section; counts are approximate.

// COMMAND ----------

// MAGIC %md
// MAGIC ## 1. Imports

// COMMAND ----------

// DBTITLE 1,Spark SQL imports
import org.apache.spark.sql.functions._

// COMMAND ----------

// MAGIC %md
// MAGIC ## 2. Data sources

// COMMAND ----------

// DBTITLE 1,Load pull request events
val pullRequestEvents = spark.table("etl.ist__dataset.pull_request_events")

// COMMAND ----------

// DBTITLE 1,Check required columns after read
val requiredPrEventColumns = Seq(
  "action",
  "is_merged",
  "merged_at",
  "created_at",
  "repo_name",
  "description",
  "title",
  "pr_number",
  "author",
  "added_lines",
  "deleted_lines",
  "changed_files"
)
val missingPrEventColumns = requiredPrEventColumns.filterNot(pullRequestEvents.columns.contains)
println(s"Expected: no missing columns from $requiredPrEventColumns")
require(missingPrEventColumns.isEmpty, s"Missing columns: ${missingPrEventColumns.mkString(", ")}")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 3. Widgets

// COMMAND ----------

// DBTITLE 1,Merge window lower bound widget
dbutils.widgets.text("mergedAtSince", "2025-01-01")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 4. Variable filters

// COMMAND ----------

// DBTITLE 1,Filter closed merged PRs from cutoff date
val mergedAtSince = dbutils.widgets.get("mergedAtSince")

val allPRs = pullRequestEvents
  .filter(col("action") === "closed")
  .filter(col("is_merged") === true)
  .filter(col("merged_at") >= mergedAtSince)

// COMMAND ----------

// DBTITLE 1,Define Rapidash and Warp Pipe classification filters
// Rapidash: explicit signature "Generated by Rapidash" in the description
val rapidashFilter =
  col("repo_name") === "itaipu" &&
  col("description").like("%Generated by Rapidash%")

// Warp Pipe: PRs that effectively create products (JM + Activity + Eligibility + Conversion)
// Excludes infra/cleanup PRs that only mention Warp Pipe
val warpPipeFilter =
  col("repo_name") === "itaipu" && (
    col("description").like("%Warp Pipe%") ||
    col("description").like("%WarpPipe%")
  ) && (
    col("title").like("%w/ Warp Pipe%") ||
    col("description").like("%Config object%") ||
    col("description").like("%productCustomerStatus%")
  )

// COMMAND ----------

// DBTITLE 1,Build AI-assisted PR population with ai_tool label
val aiPRs = allPRs
  .filter(rapidashFilter || warpPipeFilter || col("repo_name") === "cross-segment-ai-tools")
  .withColumn("ai_tool",
    when(col("repo_name") === "cross-segment-ai-tools", lit("cross-segment-ai-tools"))
    .when(col("description").like("%Generated by Rapidash%"), lit("Rapidash"))
    .otherwise(lit("Warp Pipe"))
  )

// COMMAND ----------

// MAGIC %md
// MAGIC ## 5. Functions

// COMMAND ----------

// MAGIC %md
// MAGIC Filter logic and derivations stay inline in this notebook (same behavior as the source). Extract `def` helpers only if the same transformation is reused in multiple places.

// COMMAND ----------

// MAGIC %md
// MAGIC ## 6. Code / analysis

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.1 Monthly PR volume

// COMMAND ----------

// DBTITLE 1,Aggregate monthly volume and write ai_monitor_volume_mensal
val monthlyVolume = aiPRs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    countDistinct("author").alias("unique_authors"),
    sum("added_lines").alias("total_lines_added"),
    sum("deleted_lines").alias("total_lines_deleted"),
    sum("changed_files").alias("total_files_changed")
  )
  .orderBy(col("month").desc, col("ai_tool"))

monthlyVolume.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_volume_mensal")

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.2 Breakdown by author and month

// COMMAND ----------

// DBTITLE 1,Aggregate by author and write ai_monitor_por_autor
val byAuthor = aiPRs
  .groupBy(
    date_trunc("month", col("merged_at")).alias("month"),
    col("ai_tool"),
    col("author")
  )
  .agg(
    countDistinct("pr_number").alias("prs_merged"),
    sum("added_lines").alias("lines_added"),
    sum("deleted_lines").alias("lines_deleted")
  )
  .orderBy(col("month").desc, col("prs_merged").desc)

byAuthor.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_por_autor")

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.3 Average time to merge (hours)

// COMMAND ----------

// DBTITLE 1,Compute time to merge metrics and write ai_monitor_tempo_merge
val timeToMerge = aiPRs
  .withColumn("hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 1)
  )
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    round(avg("hours_to_merge"), 1).alias("avg_hours_to_merge"),
    min("hours_to_merge").alias("min_hours"),
    max("hours_to_merge").alias("max_hours"),
    countDistinct("pr_number").alias("total_prs")
  )
  .orderBy(col("month").desc, col("ai_tool"))

timeToMerge.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_tempo_merge")

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.4 Individual PR list

// COMMAND ----------

// DBTITLE 1,Build PR list and write ai_monitor_lista_prs
val prList = aiPRs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .withColumn("hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 0)
  )
  .select(
    col("month"),
    col("ai_tool"),
    col("repo_name"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("added_lines"),
    col("deleted_lines"),
    col("changed_files"),
    col("hours_to_merge"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

prList.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_lista_prs")

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.5 AI outputs per PR (estimated attributes)
// MAGIC
// MAGIC **Counting methodology:**
// MAGIC - New Rapidash PRs: counts occurrences of `**Type**:` in the description — each attribute has exactly one type declaration
// MAGIC - Update/migration PRs (no `**Type**:`): counts attribute bullets matching `- **PascalCaseName**`
// MAGIC - Fallback: `changed_files` as minimum estimate (1 file ≈ 1 output)
// MAGIC - `cross-segment-ai-tools` PRs: counted as 1 output per PR (tools/templates, not attributes)

// COMMAND ----------

// DBTITLE 1,Derive estimated_outputs and write ai_monitor_outputs_por_pr
val typeCount = size(split(col("description"), "\\*\\*Type\\*\\*:")) - 1

val bulletCount = size(expr("filter(split(description, '\n'), x -> x rlike '^- \\\\*\\\\*[A-Z][a-zA-Z0-9]*\\\\*\\\\*')"))

val attributeCount = greatest(typeCount, bulletCount)

val withOutputs = aiPRs
  .withColumn("estimated_outputs",
    when(col("ai_tool") === "cross-segment-ai-tools", lit(1))
    .when(col("ai_tool") === "Warp Pipe", lit(1))
    .when(attributeCount > 0, attributeCount)
    .otherwise(greatest(lit(1), col("changed_files") - 2))
  )

val outputsPerPR = withOutputs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

outputsPerPR.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_por_pr")

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.6 Total AI outputs per month

// COMMAND ----------

// DBTITLE 1,Aggregate monthly outputs (write to table remains commented)
val monthlyOutputs = withOutputs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    sum("estimated_outputs").alias("total_outputs"),
    round(avg("estimated_outputs"), 1).alias("avg_outputs_per_pr"),
    countDistinct("author").alias("unique_authors")
  )
  .orderBy(col("month").desc)

// monthlyOutputs.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_mensais")

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.7 Cumulative total of AI-generated outputs

// COMMAND ----------

// DBTITLE 1,Compute cumulative totals and write ai_monitor_total_acumulado
val cumulativeTotal = withOutputs
  .agg(
    sum("estimated_outputs").alias("total_outputs_to_date"),
    countDistinct("pr_number").alias("total_prs_to_date"),
    countDistinct("author").alias("unique_authors_to_date")
  )

cumulativeTotal.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_total_acumulado")

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.8 PR content breakdown (extracted from description)
// MAGIC
// MAGIC Extracts structured fields from Rapidash PR descriptions for detailed reporting.

// COMMAND ----------

// DBTITLE 1,Extract PR content fields and write ai_monitor_pr_content
val prContent = withOutputs
  // Rapidash standard fields
  .withColumn("attribute_type",
    regexp_extract(col("description"), "\\*\\*Type\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("owner_squad",
    regexp_extract(col("description"), "\\*\\*Owner\\*\\*:\\s*(?:Squad\\.)?([^\\n]+)", 1))
  .withColumn("domain",
    regexp_extract(col("description"), "\\*\\*Domain\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("context_summary",
    regexp_extract(col("description"), "###\\s*Context\\n+([^#\\n][^\\n]{0,200})", 1))
  .withColumn("output_description",
    regexp_extract(col("description"), "\\*\\*Output[:\\*]*\\s*([^\\n]{0,200})", 1))
  // Warp Pipe: extract product name from title (e.g. "Add X Activity, Eligibility... w/ Warp Pipe")
  .withColumn("warp_pipe_product",
    regexp_extract(col("title"), "(?i)Add\\s+(.+?)\\s+(?:Activity|JM|Journey)", 1))
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("attribute_type"),
    col("owner_squad"),
    col("domain"),
    col("context_summary"),
    col("output_description"),
    col("warp_pipe_product"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

prContent.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_pr_content")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 7. Validation

// COMMAND ----------

// DBTITLE 1,Check nulls in PR keys after AI filter
val nullPrNumber = aiPRs.filter(col("pr_number").isNull).limit(1).count()
val nullMergedAt = aiPRs.filter(col("merged_at").isNull).limit(1).count()
println(s"Expected: zero rows with null pr_number -> found indicator rows: $nullPrNumber")
println(s"Expected: zero rows with null merged_at -> found indicator rows: $nullMergedAt")
require(nullPrNumber == 0, "Null pr_number in aiPRs breaks PR-grain metrics")
require(nullMergedAt == 0, "Null merged_at in aiPRs breaks time and monthly logic")

// COMMAND ----------

// DBTITLE 1,Check duplicates at repo and PR grain
val duplicateRepoPr = aiPRs
  .groupBy("repo_name", "pr_number")
  .count()
  .filter(col("count") > 1)
val hasDuplicateRepoPr = duplicateRepoPr.limit(1).count() > 0
println("Expected: no duplicate rows at (repo_name, pr_number) grain in aiPRs")
require(!hasDuplicateRepoPr, "Duplicate (repo_name, pr_number) rows detected; review upstream events")

// COMMAND ----------

// DBTITLE 1,Check merged_at range after filters
val mergedAtBounds = aiPRs.agg(
  min("merged_at").alias("min_merged_at"),
  max("merged_at").alias("max_merged_at")
)
display(mergedAtBounds)
println(s"Expected: all merged_at >= widget mergedAtSince ($mergedAtSince)")

// COMMAND ----------

// DBTITLE 1,Compare row count vs distinct repo and PR grain
val aiPrsRowCount = aiPRs.count()
val distinctRepoPrCount = aiPRs.select("repo_name", "pr_number").distinct().count()
println(s"aiPRs row count: $aiPrsRowCount")
println(s"Distinct (repo_name, pr_number): $distinctRepoPrCount")
println("Expected: row count equals distinct (repo_name, pr_number) when each PR contributes one merged row at this grain")
require(
  aiPrsRowCount == distinctRepoPrCount,
  "Row count must match distinct (repo_name, pr_number); otherwise aggregations may double-count PRs"
)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 8. Display

// COMMAND ----------

// DBTITLE 1,Display monthly volume
display(monthlyVolume)

// COMMAND ----------

// DBTITLE 1,Display breakdown by author
display(byAuthor)

// COMMAND ----------

// DBTITLE 1,Display time to merge
display(timeToMerge)

// COMMAND ----------

// DBTITLE 1,Display PR list
display(prList)

// COMMAND ----------

// DBTITLE 1,Display outputs per PR
display(outputsPerPR)

// COMMAND ----------

// DBTITLE 1,Display monthly outputs
display(monthlyOutputs)

// COMMAND ----------

// DBTITLE 1,Display cumulative total
display(cumulativeTotal)

// COMMAND ----------

// DBTITLE 1,Display PR content breakdown
display(prContent)
