// Databricks notebook source
// MAGIC %md
// MAGIC # AI-Assisted PRs Monitor (Itaipu & cross-segment-ai-tools)
// MAGIC
// MAGIC **Context**: This notebook supports monthly OKR reporting on merged pull requests that used AI-assisted tooling in the `itaipu` repository (Rapidash / Warp Pipe patterns) and all merged PRs in `cross-segment-ai-tools`.
// MAGIC
// MAGIC **Objective**: Produce monthly and cumulative metrics—volume by tool, author breakdowns, time-to-merge, PR listings, estimated AI outputs, and Rapidash/Warp Pipe content fields—for leadership reporting.
// MAGIC
// MAGIC **Method**:
// MAGIC 1. Read merged, closed PR events from a single events table (no joins).
// MAGIC 2. Apply a fixed merged-since cutoff and classify rows into `ai_tool` (Rapidash, Warp Pipe, cross-segment-ai-tools).
// MAGIC 3. Build aggregations and detail extracts; materialize curated Delta tables for dashboards and ad hoc use.
// MAGIC 4. Run sanity checks on filters, grain, columns, and aggregation safety.
// MAGIC
// MAGIC **Analysis structure**:
// MAGIC - 0. Intro / README (this block)
// MAGIC - 1. Imports
// MAGIC - 2. Data sources
// MAGIC - 3. Widgets
// MAGIC - 4. Variable filters
// MAGIC - 5. Functions
// MAGIC - 6. Code / analysis
// MAGIC - 7. Validation
// MAGIC - 8. Display
// MAGIC
// MAGIC **Data sources**:
// MAGIC - `etl.ist__dataset.pull_request_events` — single base for all metrics (event-level rows; PR-level metrics use `countDistinct` / careful sums where documented).
// MAGIC
// MAGIC **Assumptions and caveats**:
// MAGIC - Rapidash detection uses the phrase `Generated by Rapidash` in the description; Warp Pipe uses combined title/description heuristics (see filters below).
// MAGIC - `cross-segment-ai-tools` PRs are counted as one estimated output per PR by design.
// MAGIC - Estimated output counts for Rapidash use description parsing; line/file sums can be inflated if multiple event rows exist per PR (see validation).

// COMMAND ----------

// MAGIC %md
// MAGIC ## 1. Imports

// COMMAND ----------

// DBTITLE 1,Imports
import org.apache.spark.sql.DataFrame
import org.apache.spark.sql.functions._

// COMMAND ----------

// MAGIC %md
// MAGIC ## 2. Data sources

// COMMAND ----------

// DBTITLE 1,Declare pull request events table
val pullRequestEventsTable = "etl.ist__dataset.pull_request_events"

// COMMAND ----------

// DBTITLE 1,Load pull request events (lazy)
val pullRequestEvents = spark.table(pullRequestEventsTable)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 3. Widgets

// COMMAND ----------

// DBTITLE 1,Parameters for merged-since cutoff
dbutils.widgets.text("mergedSince", "2025-01-01")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 4. Variable filters

// COMMAND ----------

// DBTITLE 1,Resolved cutoff and merged-PR scope
val mergedSince = dbutils.widgets.get("mergedSince")

val mergedClosedPullRequests = pullRequestEvents
  .filter(col("action") === "closed")
  .filter(col("is_merged") === true)
  .filter(col("merged_at") >= mergedSince)

// Rapidash: explicit signature "Generated by Rapidash" in the description
val rapidashFilter =
  col("repo_name") === "itaipu" &&
  col("description").like("%Generated by Rapidash%")

// Warp Pipe: PRs that effectively create products (JM + Activity + Eligibility + Conversion)
// Excludes infra/cleanup PRs that only mention Warp Pipe
val warpPipeFilter =
  col("repo_name") === "itaipu" && (
    col("description").like("%Warp Pipe%") ||
    col("description").like("%WarpPipe%")
  ) && (
    col("title").like("%w/ Warp Pipe%") ||
    col("description").like("%Config object%") ||
    col("description").like("%productCustomerStatus%")
  )

val crossSegmentRepoFilter = col("repo_name") === "cross-segment-ai-tools"

// COMMAND ----------

// MAGIC %md
// MAGIC ## 5. Functions

// COMMAND ----------

// DBTITLE 1,Classify AI tool label
def withAiToolColumn(base: DataFrame): DataFrame = {
  base
    .withColumn(
      "ai_tool",
      when(col("repo_name") === "cross-segment-ai-tools", lit("cross-segment-ai-tools"))
        .when(col("description").like("%Generated by Rapidash%"), lit("Rapidash"))
        .otherwise(lit("Warp Pipe"))
    )
}

// COMMAND ----------

// MAGIC %md
// MAGIC ## 6. Code / analysis

// COMMAND ----------

// DBTITLE 1,Build AI-assisted PR population (single-table filters only)
val aiAssistedPullRequests = withAiToolColumn(
  mergedClosedPullRequests.filter(rapidashFilter || warpPipeFilter || crossSegmentRepoFilter)
)

// COMMAND ----------

// DBTITLE 1,Monthly PR volume
val monthlyVolume = aiAssistedPullRequests
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    countDistinct("author").alias("unique_authors"),
    sum("added_lines").alias("total_lines_added"),
    sum("deleted_lines").alias("total_lines_deleted"),
    sum("changed_files").alias("total_files_changed")
  )
  .orderBy(col("month").desc, col("ai_tool"))

monthlyVolume.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_volume_mensal")

// COMMAND ----------

// DBTITLE 1,Breakdown by author and month
val byAuthor = aiAssistedPullRequests
  .groupBy(
    date_trunc("month", col("merged_at")).alias("month"),
    col("ai_tool"),
    col("author")
  )
  .agg(
    countDistinct("pr_number").alias("prs_merged"),
    sum("added_lines").alias("lines_added"),
    sum("deleted_lines").alias("lines_deleted")
  )
  .orderBy(col("month").desc, col("prs_merged").desc)

byAuthor.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_por_autor")

// COMMAND ----------

// DBTITLE 1,Average time to merge (hours)
val timeToMerge = aiAssistedPullRequests
  .withColumn(
    "hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 1)
  )
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    round(avg("hours_to_merge"), 1).alias("avg_hours_to_merge"),
    min("hours_to_merge").alias("min_hours"),
    max("hours_to_merge").alias("max_hours"),
    countDistinct("pr_number").alias("total_prs")
  )
  .orderBy(col("month").desc, col("ai_tool"))

timeToMerge.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_tempo_merge")

// COMMAND ----------

// DBTITLE 1,Individual PR list
val prList = aiAssistedPullRequests
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .withColumn(
    "hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 0)
  )
  .select(
    col("month"),
    col("ai_tool"),
    col("repo_name"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("added_lines"),
    col("deleted_lines"),
    col("changed_files"),
    col("hours_to_merge"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

prList.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_lista_prs")

// COMMAND ----------

// DBTITLE 1,Estimated AI outputs per PR
// Counting methodology (unchanged):
// - New Rapidash PRs: counts occurrences of `**Type**:` in the description — each attribute has exactly one type declaration
// - Update/migration PRs (no `**Type**:`): counts attribute bullets matching `- **PascalCaseName**`
// - Fallback: `changed_files` as minimum estimate (1 file ≈ 1 output)
// - `cross-segment-ai-tools` PRs: counted as 1 output per PR (tools/templates, not attributes)
val typeCount = size(split(col("description"), "\\*\\*Type\\*\\*:")) - 1

val bulletCount = size(expr("filter(split(description, '\n'), x -> x rlike '^- \\\\*\\\\*[A-Z][a-zA-Z0-9]*\\\\*\\\\*')"))

val attributeCount = greatest(typeCount, bulletCount)

val withOutputs = aiAssistedPullRequests
  .withColumn(
    "estimated_outputs",
    when(col("ai_tool") === "cross-segment-ai-tools", lit(1))
      .when(col("ai_tool") === "Warp Pipe", lit(1))
      .when(attributeCount > 0, attributeCount)
      .otherwise(greatest(lit(1), col("changed_files") - 2))
  )

val outputsPerPR = withOutputs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

outputsPerPR.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_por_pr")

// COMMAND ----------

// DBTITLE 1,Total AI outputs per month
val monthlyOutputs = withOutputs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    sum("estimated_outputs").alias("total_outputs"),
    round(avg("estimated_outputs"), 1).alias("avg_outputs_per_pr"),
    countDistinct("author").alias("unique_authors")
  )
  .orderBy(col("month").desc)

// monthlyOutputs.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_mensais")

// COMMAND ----------

// DBTITLE 1,Cumulative total of AI-generated outputs
val cumulativeTotal = withOutputs
  .agg(
    sum("estimated_outputs").alias("total_outputs_to_date"),
    countDistinct("pr_number").alias("total_prs_to_date"),
    countDistinct("author").alias("unique_authors_to_date")
  )

cumulativeTotal.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_total_acumulado")

// COMMAND ----------

// DBTITLE 1,PR content breakdown (extracted from description)
val prContent = withOutputs
  .withColumn("attribute_type",
    regexp_extract(col("description"), "\\*\\*Type\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("owner_squad",
    regexp_extract(col("description"), "\\*\\*Owner\\*\\*:\\s*(?:Squad\\.)?([^\\n]+)", 1))
  .withColumn("domain",
    regexp_extract(col("description"), "\\*\\*Domain\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("context_summary",
    regexp_extract(col("description"), "###\\s*Context\\n+([^#\\n][^\\n]{0,200})", 1))
  .withColumn("output_description",
    regexp_extract(col("description"), "\\*\\*Output[:\\*]*\\s*([^\\n]{0,200})", 1))
  .withColumn("warp_pipe_product",
    regexp_extract(col("title"), "(?i)Add\\s+(.+?)\\s+(?:Activity|JM|Journey)", 1))
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("attribute_type"),
    col("owner_squad"),
    col("domain"),
    col("context_summary"),
    col("output_description"),
    col("warp_pipe_product"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

prContent.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_pr_content")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 7. Validation
// MAGIC
// MAGIC **Joins**: This notebook does **not** perform any joins. All logic is built from `etl.ist__dataset.pull_request_events` using filters and derived columns. The checks below therefore focus on filter impact, required columns, duplicate grain, and aggregation safety instead of join coverage.

// COMMAND ----------

// DBTITLE 1,Confirm no joins — validate scope explicitly
println(
  """Pipeline shape: single-source — no joins.
    |Checks: required columns, filter narrowing, PR-grain duplicates, merged_at bounds, row vs distinct-PR inflation for sums.""".stripMargin
)

// COMMAND ----------

// DBTITLE 1,Check required columns after read
val requiredColumns = Seq(
  "action",
  "is_merged",
  "merged_at",
  "repo_name",
  "description",
  "title",
  "pr_number",
  "author",
  "added_lines",
  "deleted_lines",
  "changed_files",
  "created_at"
)
val missingRequiredColumns = requiredColumns.filterNot(pullRequestEvents.columns.contains)
println(s"Required columns: ${requiredColumns.mkString(", ")}")
require(
  missingRequiredColumns.isEmpty,
  s"Missing required columns on $pullRequestEventsTable: ${missingRequiredColumns.mkString(", ")}"
)

// COMMAND ----------

// DBTITLE 1,Validate filter impact — merged cohort vs AI subset at PR grain
val distinctPrMergedCohort = mergedClosedPullRequests.select("repo_name", "pr_number").distinct().count()
val distinctPrAiSubset = aiAssistedPullRequests.select("repo_name", "pr_number").distinct().count()
println(s"Distinct (repo_name, pr_number) after closed + merged + merged_at >= $mergedSince: $distinctPrMergedCohort")
println(s"Distinct (repo_name, pr_number) after AI classification filters: $distinctPrAiSubset")
println("Expected: AI subset count <= merged cohort count.")

// COMMAND ----------

// DBTITLE 1,Check duplicates at PR grain in AI population
val duplicatePrGroups = aiAssistedPullRequests
  .groupBy("repo_name", "pr_number")
  .count()
  .filter(col("count") > 1)

val duplicatePrGroupCount = duplicatePrGroups.count()
println(s"PR groups with more than one row in aiAssistedPullRequests: $duplicatePrGroupCount")
println("Expected: 0 for a clean PR grain; if > 0, sum() on lines/files double-counts unless deduplicated.")
display(duplicatePrGroups.limit(50))

// COMMAND ----------

// DBTITLE 1,Min and max merged_at after AI filters
display(
  aiAssistedPullRequests.agg(
    min(col("merged_at")).alias("min_merged_at"),
    max(col("merged_at")).alias("max_merged_at")
  )
)
println(s"Expected: min merged_at >= $mergedSince (string cutoff applied to timestamp column — verify type semantics in production).")

// COMMAND ----------

// DBTITLE 1,Aggregation safety — rows vs distinct PRs and sum exposure
val aiRowCount = aiAssistedPullRequests.count()
val aiDistinctPrCount = aiAssistedPullRequests.select("repo_name", "pr_number").distinct().count()
println(s"Rows in aiAssistedPullRequests: $aiRowCount")
println(s"Distinct (repo_name, pr_number): $aiDistinctPrCount")
println(
  """PR-count metrics use countDistinct(pr_number) (with month/author grouping as in analysis).
    |Line and file totals use sum() across rows — inflated when multiple rows exist per PR.""".stripMargin
)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 8. Display

// COMMAND ----------

// DBTITLE 1,Display monthly volume
display(monthlyVolume)

// COMMAND ----------

// DBTITLE 1,Display author breakdown
display(byAuthor)

// COMMAND ----------

// DBTITLE 1,Display time to merge
display(timeToMerge)

// COMMAND ----------

// DBTITLE 1,Display PR list
display(prList)

// COMMAND ----------

// DBTITLE 1,Display outputs per PR
display(outputsPerPR)

// COMMAND ----------

// DBTITLE 1,Display monthly outputs (table write remains commented in analysis)
display(monthlyOutputs)

// COMMAND ----------

// DBTITLE 1,Display cumulative totals
display(cumulativeTotal)

// COMMAND ----------

// DBTITLE 1,Display PR content extract
display(prContent)
