// Databricks notebook source
// MAGIC %md
// MAGIC # AI-Assisted PRs Monitor
// MAGIC Tracks PRs created with AI assistance in the `itaipu` (Rapidash / Warp Pipe) and `cross-segment-ai-tools` (all PRs) repositories.
// MAGIC Used for monthly OKR reporting.

// COMMAND ----------

import org.apache.spark.sql.functions._

val allPRs = spark.table("etl.ist__dataset.pull_request_events")
  .filter(col("action") === "closed")
  .filter(col("is_merged") === true)
  .filter(col("merged_at") >= "2025-01-01")

// Rapidash: explicit signature "Generated by Rapidash" in the description
val rapidashFilter =
  col("repo_name") === "itaipu" &&
  col("description").like("%Generated by Rapidash%")

// Warp Pipe: PRs that effectively create products (JM + Activity + Eligibility + Conversion)
// Excludes infra/cleanup PRs that only mention Warp Pipe
val warpPipeFilter =
  col("repo_name") === "itaipu" && (
    col("description").like("%Warp Pipe%") ||
    col("description").like("%WarpPipe%")
  ) && (
    col("title").like("%w/ Warp Pipe%") ||
    col("description").like("%Config object%") ||
    col("description").like("%productCustomerStatus%")
  )

val aiPRs = allPRs
  .filter(rapidashFilter || warpPipeFilter || col("repo_name") === "cross-segment-ai-tools")
  .withColumn("ai_tool",
    when(col("repo_name") === "cross-segment-ai-tools", lit("cross-segment-ai-tools"))
    .when(col("description").like("%Generated by Rapidash%"), lit("Rapidash"))
    .otherwise(lit("Warp Pipe"))
  )

// COMMAND ----------

// MAGIC %md
// MAGIC ## 1. Monthly PR volume

// COMMAND ----------

val monthlyVolume = aiPRs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    countDistinct("author").alias("unique_authors"),
    sum("added_lines").alias("total_lines_added"),
    sum("deleted_lines").alias("total_lines_deleted"),
    sum("changed_files").alias("total_files_changed")
  )
  .orderBy(col("month").desc, col("ai_tool"))

monthlyVolume.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_volume_mensal")
display(monthlyVolume)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 2. Breakdown by author and month

// COMMAND ----------

val byAuthor = aiPRs
  .groupBy(
    date_trunc("month", col("merged_at")).alias("month"),
    col("ai_tool"),
    col("author")
  )
  .agg(
    countDistinct("pr_number").alias("prs_merged"),
    sum("added_lines").alias("lines_added"),
    sum("deleted_lines").alias("lines_deleted")
  )
  .orderBy(col("month").desc, col("prs_merged").desc)

byAuthor.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_por_autor")
display(byAuthor)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 3. Average time to merge (hours)

// COMMAND ----------

val timeToMerge = aiPRs
  .withColumn("hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 1)
  )
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    round(avg("hours_to_merge"), 1).alias("avg_hours_to_merge"),
    min("hours_to_merge").alias("min_hours"),
    max("hours_to_merge").alias("max_hours"),
    countDistinct("pr_number").alias("total_prs")
  )
  .orderBy(col("month").desc, col("ai_tool"))

timeToMerge.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_tempo_merge")
display(timeToMerge)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 4. Individual PR list

// COMMAND ----------

val prList = aiPRs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .withColumn("hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 0)
  )
  .select(
    col("month"),
    col("ai_tool"),
    col("repo_name"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("added_lines"),
    col("deleted_lines"),
    col("changed_files"),
    col("hours_to_merge"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

prList.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_lista_prs")
display(prList)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 5. AI outputs per PR (estimated attributes)
// MAGIC
// MAGIC **Counting methodology:**
// MAGIC - New Rapidash PRs: counts occurrences of `**Type**:` in the description — each attribute has exactly one type declaration
// MAGIC - Update/migration PRs (no `**Type**:`): counts attribute bullets matching `- **PascalCaseName**`
// MAGIC - Fallback: `changed_files` as minimum estimate (1 file ≈ 1 output)
// MAGIC - `cross-segment-ai-tools` PRs: counted as 1 output per PR (tools/templates, not attributes)

// COMMAND ----------

val typeCount = size(split(col("description"), "\\*\\*Type\\*\\*:")) - 1

val bulletCount = size(expr("filter(split(description, '\n'), x -> x rlike '^- \\\\*\\\\*[A-Z][a-zA-Z0-9]*\\\\*\\\\*')"))

val attributeCount = greatest(typeCount, bulletCount)

val withOutputs = aiPRs
  .withColumn("estimated_outputs",
    when(col("ai_tool") === "cross-segment-ai-tools", lit(1))
    .when(col("ai_tool") === "Warp Pipe", lit(1))
    .when(attributeCount > 0, attributeCount)
    .otherwise(greatest(lit(1), col("changed_files") - 2))
  )

val outputsPerPR = withOutputs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

outputsPerPR.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_por_pr")
display(outputsPerPR)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 6. Total AI outputs per month

// COMMAND ----------

val monthlyOutputs = withOutputs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    sum("estimated_outputs").alias("total_outputs"),
    round(avg("estimated_outputs"), 1).alias("avg_outputs_per_pr"),
    countDistinct("author").alias("unique_authors")
  )
  .orderBy(col("month").desc)

// monthlyOutputs.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_mensais")
display(monthlyOutputs)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 7. Cumulative total of AI-generated outputs

// COMMAND ----------

val cumulativeTotal = withOutputs
  .agg(
    sum("estimated_outputs").alias("total_outputs_to_date"),
    countDistinct("pr_number").alias("total_prs_to_date"),
    countDistinct("author").alias("unique_authors_to_date")
  )

cumulativeTotal.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_total_acumulado")
display(cumulativeTotal)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 8. PR content breakdown (extracted from description)
// MAGIC
// MAGIC Extracts structured fields from Rapidash PR descriptions for detailed reporting.

// COMMAND ----------

val prContent = withOutputs
  // Rapidash standard fields
  .withColumn("attribute_type",
    regexp_extract(col("description"), "\\*\\*Type\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("owner_squad",
    regexp_extract(col("description"), "\\*\\*Owner\\*\\*:\\s*(?:Squad\\.)?([^\\n]+)", 1))
  .withColumn("domain",
    regexp_extract(col("description"), "\\*\\*Domain\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("context_summary",
    regexp_extract(col("description"), "###\\s*Context\\n+([^#\\n][^\\n]{0,200})", 1))
  .withColumn("output_description",
    regexp_extract(col("description"), "\\*\\*Output[:\\*]*\\s*([^\\n]{0,200})", 1))
  // Warp Pipe: extract product name from title (e.g. "Add X Activity, Eligibility... w/ Warp Pipe")
  .withColumn("warp_pipe_product",
    regexp_extract(col("title"), "(?i)Add\\s+(.+?)\\s+(?:Activity|JM|Journey)", 1))
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("attribute_type"),
    col("owner_squad"),
    col("domain"),
    col("context_summary"),
    col("output_description"),
    col("warp_pipe_product"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

prContent.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_pr_content")
display(prContent)