// Databricks notebook source
// MAGIC %md
// MAGIC # AI-Assisted Pull Requests Monitor — Itaipu & Cross-Segment AI Tools
// MAGIC
// MAGIC **Context**: This notebook supports **monthly OKR reporting** on merged pull requests that used AI-assisted workflows in the `itaipu` (Rapidash / Warp Pipe) and `cross-segment-ai-tools` repositories.
// MAGIC
// MAGIC **Objective**: Quantify merged AI-assisted PR volume, authors, line changes, time-to-merge, and estimated AI outputs for leadership reporting.
// MAGIC
// MAGIC **Method**:
// MAGIC 1. Read merged, closed PR events from the institutional pull-request events table.
// MAGIC 2. Apply repository-specific heuristics (Rapidash signature, Warp Pipe product patterns, all PRs from `cross-segment-ai-tools`).
// MAGIC 3. Label each row with `ai_tool` and build monthly aggregates, author breakdowns, timing metrics, output estimates, and content extracts.
// MAGIC 4. Materialize results to Delta tables under `usr.br__customer_lifecycle_optimization` and display final outputs.
// MAGIC
// MAGIC **Analysis structure**:
// MAGIC - 0. Intro / README (this block)
// MAGIC - 1. Imports
// MAGIC - 2. Data sources
// MAGIC - 3. Widgets
// MAGIC - 4. Variable filters
// MAGIC - 5. Functions
// MAGIC - 6. Code / analysis
// MAGIC - 7. Validation
// MAGIC - 8. Display
// MAGIC
// MAGIC **Data sources**:
// MAGIC - `etl.ist__dataset.pull_request_events` — single source for closed, merged PR events and metadata (no joins to other tables in this notebook).
// MAGIC
// MAGIC **Main assumptions**:
// MAGIC - `action === "closed"` and `is_merged === true` define the merged-PR population.
// MAGIC - `merged_at >= 2025-01-01` is the reporting window.
// MAGIC - Rapidash PRs are identified by `itaipu` and `Generated by Rapidash` in the description.
// MAGIC - Warp Pipe PRs use additional title/description patterns to exclude infra-only mentions.
// MAGIC - `cross-segment-ai-tools` counts every merged PR as one AI-assisted PR with tool label `cross-segment-ai-tools`.
// MAGIC - Estimated output counts for Rapidash use description parsing; methodology is approximate (see section 6 notes).

// COMMAND ----------

// MAGIC %md
// MAGIC ## 1. Imports

// COMMAND ----------

// DBTITLE 1,Spark SQL imports
import org.apache.spark.sql.DataFrame
import org.apache.spark.sql.functions._

// COMMAND ----------

// MAGIC %md
// MAGIC ## 2. Data sources

// COMMAND ----------

// DBTITLE 1,Load pull request events
val pullRequestEvents: DataFrame = spark.table("etl.ist__dataset.pull_request_events")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 3. Widgets
// MAGIC
// MAGIC No runtime widgets; scope is fixed in **Variable filters** (merged PRs, `merged_at` cutoff, repository logic as agreed for OKR reporting).

// COMMAND ----------

// DBTITLE 1,No widgets placeholder
()
// Parameters are constants in section 4 (no runtime widgets).

// COMMAND ----------

// MAGIC %md
// MAGIC ## 4. Variable filters

// COMMAND ----------

// DBTITLE 1,Notebook scope and cutoff
val mergedAtLowerBound = "2025-01-01"

// Rapidash: explicit signature "Generated by Rapidash" in the description
val rapidashFilter: org.apache.spark.sql.Column =
  col("repo_name") === "itaipu" &&
    col("description").like("%Generated by Rapidash%")

// Warp Pipe: PRs that effectively create products (JM + Activity + Eligibility + Conversion)
// Excludes infra/cleanup PRs that only mention Warp Pipe
val warpPipeFilter: org.apache.spark.sql.Column =
  col("repo_name") === "itaipu" && (
    col("description").like("%Warp Pipe%") ||
      col("description").like("%WarpPipe%")
  ) && (
    col("title").like("%w/ Warp Pipe%") ||
      col("description").like("%Config object%") ||
      col("description").like("%productCustomerStatus%")
  )

val mergedClosedPullRequestEvents: DataFrame = pullRequestEvents
  .filter(col("action") === "closed")
  .filter(col("is_merged") === true)
  .filter(col("merged_at") >= mergedAtLowerBound)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 5. Functions

// COMMAND ----------

// DBTITLE 1,Label AI tool from repository and description
def withAiToolColumn(df: DataFrame): DataFrame = {
  df.withColumn(
    "ai_tool",
    when(col("repo_name") === "cross-segment-ai-tools", lit("cross-segment-ai-tools"))
      .when(col("description").like("%Generated by Rapidash%"), lit("Rapidash"))
      .otherwise(lit("Warp Pipe"))
  )
}

// COMMAND ----------

// MAGIC %md
// MAGIC ## 6. Code / analysis

// COMMAND ----------

// DBTITLE 1,Build AI-assisted merged PR population
val aiAssistedMergedPullRequests: DataFrame = withAiToolColumn(
  mergedClosedPullRequestEvents
    .filter(rapidashFilter || warpPipeFilter || col("repo_name") === "cross-segment-ai-tools")
)

// COMMAND ----------

// DBTITLE 1,Monthly PR volume
val monthlyVolume = aiAssistedMergedPullRequests
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    countDistinct("author").alias("unique_authors"),
    sum("added_lines").alias("total_lines_added"),
    sum("deleted_lines").alias("total_lines_deleted"),
    sum("changed_files").alias("total_files_changed")
  )
  .orderBy(col("month").desc, col("ai_tool"))

monthlyVolume.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_volume_mensal"
)

// COMMAND ----------

// DBTITLE 1,Breakdown by author and month
val byAuthor = aiAssistedMergedPullRequests
  .groupBy(
    date_trunc("month", col("merged_at")).alias("month"),
    col("ai_tool"),
    col("author")
  )
  .agg(
    countDistinct("pr_number").alias("prs_merged"),
    sum("added_lines").alias("lines_added"),
    sum("deleted_lines").alias("lines_deleted")
  )
  .orderBy(col("month").desc, col("prs_merged").desc)

byAuthor.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_por_autor"
)

// COMMAND ----------

// DBTITLE 1,Average time to merge in hours
val timeToMerge = aiAssistedMergedPullRequests
  .withColumn(
    "hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 1)
  )
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    round(avg("hours_to_merge"), 1).alias("avg_hours_to_merge"),
    min("hours_to_merge").alias("min_hours"),
    max("hours_to_merge").alias("max_hours"),
    countDistinct("pr_number").alias("total_prs")
  )
  .orderBy(col("month").desc, col("ai_tool"))

timeToMerge.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_tempo_merge"
)

// COMMAND ----------

// DBTITLE 1,Individual PR list
val prList = aiAssistedMergedPullRequests
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .withColumn(
    "hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 0)
  )
  .select(
    col("month"),
    col("ai_tool"),
    col("repo_name"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("added_lines"),
    col("deleted_lines"),
    col("changed_files"),
    col("hours_to_merge"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

prList.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_lista_prs"
)

// COMMAND ----------

// MAGIC %md
// MAGIC ### Estimated AI outputs per PR
// MAGIC
// MAGIC **Counting methodology**:
// MAGIC - New Rapidash PRs: counts occurrences of `**Type**:` in the description — each attribute has exactly one type declaration
// MAGIC - Update/migration PRs (no `**Type**:`): counts attribute bullets matching `- **PascalCaseName**`
// MAGIC - Fallback: `changed_files` as minimum estimate (1 file ≈ 1 output)
// MAGIC - `cross-segment-ai-tools` PRs: counted as 1 output per PR (tools/templates, not attributes)

// COMMAND ----------

// DBTITLE 1,Estimated outputs per PR
val typeCount = size(split(col("description"), "\\*\\*Type\\*\\*:")) - 1

val bulletCount = size(expr("filter(split(description, '\n'), x -> x rlike '^- \\\\*\\\\*[A-Z][a-zA-Z0-9]*\\\\*\\\\*')"))

val attributeCount = greatest(typeCount, bulletCount)

val withOutputs = aiAssistedMergedPullRequests
  .withColumn(
    "estimated_outputs",
    when(col("ai_tool") === "cross-segment-ai-tools", lit(1))
      .when(col("ai_tool") === "Warp Pipe", lit(1))
      .when(attributeCount > 0, attributeCount)
      .otherwise(greatest(lit(1), col("changed_files") - 2))
  )

val outputsPerPR = withOutputs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

outputsPerPR.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_outputs_por_pr"
)

// COMMAND ----------

// DBTITLE 1,Total AI outputs per month
val monthlyOutputs = withOutputs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    sum("estimated_outputs").alias("total_outputs"),
    round(avg("estimated_outputs"), 1).alias("avg_outputs_per_pr"),
    countDistinct("author").alias("unique_authors")
  )
  .orderBy(col("month").desc)

// monthlyOutputs.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_mensais")
monthlyOutputs // materialization intentionally commented in source notebook; kept aligned

// COMMAND ----------

// DBTITLE 1,Cumulative total of AI-generated outputs
val cumulativeTotal = withOutputs
  .agg(
    sum("estimated_outputs").alias("total_outputs_to_date"),
    countDistinct("pr_number").alias("total_prs_to_date"),
    countDistinct("author").alias("unique_authors_to_date")
  )

cumulativeTotal.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_total_acumulado"
)

// COMMAND ----------

// DBTITLE 1,PR content breakdown from description
val prContent = withOutputs
  .withColumn("attribute_type", regexp_extract(col("description"), "\\*\\*Type\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("owner_squad", regexp_extract(col("description"), "\\*\\*Owner\\*\\*:\\s*(?:Squad\\.)?([^\\n]+)", 1))
  .withColumn("domain", regexp_extract(col("description"), "\\*\\*Domain\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("context_summary", regexp_extract(col("description"), "###\\s*Context\\n+([^#\\n][^\\n]{0,200})", 1))
  .withColumn("output_description", regexp_extract(col("description"), "\\*\\*Output[:\\*]*\\s*([^\\n]{0,200})", 1))
  .withColumn("warp_pipe_product", regexp_extract(col("title"), "(?i)Add\\s+(.+?)\\s+(?:Activity|JM|Journey)", 1))
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("attribute_type"),
    col("owner_squad"),
    col("domain"),
    col("context_summary"),
    col("output_description"),
    col("warp_pipe_product"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

prContent.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_pr_content"
)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 7. Validation
// MAGIC
// MAGIC **Joins**: This notebook performs **no joins**. All metrics are derived from `etl.ist__dataset.pull_request_events` only. Validations below cover filter impact, required columns, duplicate risk at PR grain, and aggregation safety instead of join coverage.

// COMMAND ----------

// DBTITLE 1,Assert required columns exist on merged closed events
val requiredColumnsForPipeline = Seq(
  "action",
  "is_merged",
  "merged_at",
  "repo_name",
  "description",
  "title",
  "pr_number",
  "author",
  "added_lines",
  "deleted_lines",
  "changed_files",
  "created_at"
)

val missingAfterRead = requiredColumnsForPipeline.filterNot(mergedClosedPullRequestEvents.columns.contains)
require(missingAfterRead.isEmpty, s"Missing required columns after read/filters: ${missingAfterRead.mkString(", ")}")

// COMMAND ----------

// DBTITLE 1,Measure filter impact from raw table to AI-assisted population
val rawRowCount = pullRequestEvents.count()
val afterMergedClosedCount = mergedClosedPullRequestEvents.count()
val aiAssistedCount = aiAssistedMergedPullRequests.count()

println(s"Rows in pull_request_events (full table): $rawRowCount")
println(s"Rows after merged+closed+merged_at>=$mergedAtLowerBound: $afterMergedClosedCount")
println(s"Rows after AI repo/heuristic filter: $aiAssistedCount")

// COMMAND ----------

// DBTITLE 1,Check duplicate risk at repo and PR number grain
val prGrainDupes = aiAssistedMergedPullRequests
  .groupBy("repo_name", "pr_number")
  .count()
  .filter(col("count") > 1)

val duplicatePrGrainRows = prGrainDupes.count()
println(s"Duplicate (repo_name, pr_number) groups in AI-assisted population: $duplicatePrGrainRows")
if (duplicatePrGrainRows > 0) {
  println("Warning: multiple event rows per PR; countDistinct(pr_number) in aggregations avoids double-counting PRs but sums of lines/files may multiply across duplicate rows.")
}

// COMMAND ----------

// DBTITLE 1,Validate merged_at range after filters
val mergedAtBounds = mergedClosedPullRequestEvents.agg(
  min("merged_at").alias("min_merged_at"),
  max("merged_at").alias("max_merged_at")
)
display(mergedAtBounds)

// COMMAND ----------

// DBTITLE 1,Aggregation safety — PR distinct count vs row count
val distinctPrsInAiPopulation = aiAssistedMergedPullRequests.select("repo_name", "pr_number").distinct().count()
println(s"Distinct (repo_name, pr_number) in AI-assisted population: $distinctPrsInAiPopulation")
println(s"Row count (may exceed distinct PRs if multiple events per PR): $aiAssistedCount")

// COMMAND ----------

// DBTITLE 1,Aggregation safety — cumulative distinct PRs match base population
val globalDistinctPrNumber = aiAssistedMergedPullRequests.select("pr_number").distinct().count()
val cumulativePrsFromAgg = cumulativeTotal.select("total_prs_to_date").first().getLong(0)
println(s"countDistinct(pr_number) on AI-assisted population: $globalDistinctPrNumber")
println(s"cumulativeTotal.total_prs_to_date: $cumulativePrsFromAgg")
require(
  globalDistinctPrNumber == cumulativePrsFromAgg,
  s"Mismatch between global countDistinct(pr_number) ($globalDistinctPrNumber) and cumulative aggregate ($cumulativePrsFromAgg)"
)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 8. Display

// COMMAND ----------

// DBTITLE 1,Display monthly volume
display(monthlyVolume)

// COMMAND ----------

// DBTITLE 1,Display breakdown by author
display(byAuthor)

// COMMAND ----------

// DBTITLE 1,Display time to merge
display(timeToMerge)

// COMMAND ----------

// DBTITLE 1,Display PR list
display(prList)

// COMMAND ----------

// DBTITLE 1,Display outputs per PR
display(outputsPerPR)

// COMMAND ----------

// DBTITLE 1,Display monthly outputs
display(monthlyOutputs)

// COMMAND ----------

// DBTITLE 1,Display cumulative totals
display(cumulativeTotal)

// COMMAND ----------

// DBTITLE 1,Display PR content breakdown
display(prContent)
