// Databricks notebook source
// MAGIC %md
// MAGIC # AI-Assisted PRs Monitor
// MAGIC
// MAGIC **Context**: This notebook supports **monthly OKR reporting** on pull requests that were created with AI assistance, focusing on the `itaipu` (Rapidash / Warp Pipe) and `cross-segment-ai-tools` repositories.
// MAGIC
// MAGIC **Objective**: Produce stable monthly and PR-level metrics (volume, authors, lines, time to merge, estimated outputs, and Rapidash/Warp Pipe content fields) and materialize them to the existing Delta tables used by stakeholders.
// MAGIC
// MAGIC **Method**:
// MAGIC 1. Read merged, closed PR events from the IST pull request events dataset
// MAGIC 2. Classify PRs into Rapidash, Warp Pipe, or cross-segment AI tools using the same filters as the legacy notebook
// MAGIC 3. Build aggregations and PR-level extracts
// MAGIC 4. Validate required columns, PR grain, and aggregation safety before writing
// MAGIC 5. Overwrite the output tables and display results for inspection
// MAGIC
// MAGIC **Analysis structure**:
// MAGIC - 0. Intro / README (this block)
// MAGIC - 1. Imports
// MAGIC - 2. Data sources
// MAGIC - 3. Widgets
// MAGIC - 4. Variable filters
// MAGIC - 5. Functions
// MAGIC - 6. Code / analysis
// MAGIC - 7. Validation
// MAGIC - 8. Display and persistence
// MAGIC
// MAGIC **Data sources**:
// MAGIC - `etl.ist__dataset.pull_request_events` — event-level pull request records; grain is one row per event; this pipeline uses merged, closed PR rows and treats each `(repo_name, pr_number)` as one logical PR after filters.
// MAGIC
// MAGIC **Assumptions**:
// MAGIC - `merged_at` on or after the widget cutoff is the reporting window for merges.
// MAGIC - `countDistinct("pr_number")` in aggregations matches business expectations (if `pr_number` were ever reused across repos, metrics would need a composite key — an explicit check below compares against `(repo_name, pr_number)`).

// COMMAND ----------

// MAGIC %md
// MAGIC ## 1. Imports

// COMMAND ----------

// DBTITLE 1,Imports
import org.apache.spark.sql.DataFrame
import org.apache.spark.sql.functions._

// COMMAND ----------

// MAGIC %md
// MAGIC ## 2. Data sources

// COMMAND ----------

// DBTITLE 1,Load pull request events
val pullRequestEvents = spark.table("etl.ist__dataset.pull_request_events")

// COMMAND ----------

// DBTITLE 1,Check required columns after read
val requiredPullRequestColumns = Seq(
  "action",
  "is_merged",
  "merged_at",
  "repo_name",
  "description",
  "title",
  "pr_number",
  "author",
  "added_lines",
  "deleted_lines",
  "changed_files",
  "created_at"
)

val missingPullRequestColumns =
  requiredPullRequestColumns.filterNot(pullRequestEvents.columns.contains)

println(s"Expected: zero missing required columns -> $requiredPullRequestColumns")
require(
  missingPullRequestColumns.isEmpty,
  s"Missing columns: ${missingPullRequestColumns.mkString(", ")}"
)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 3. Widgets

// COMMAND ----------

// DBTITLE 1,Merge window widget
dbutils.widgets.text("mergedSince", "2025-01-01")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 4. Variable filters

// COMMAND ----------

// DBTITLE 1,Read widget parameters
val mergedSince = dbutils.widgets.get("mergedSince")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 5. Functions

// COMMAND ----------

// DBTITLE 1,Build AI-assisted PR population
def buildAiAssistedPullRequests(events: DataFrame, mergedSinceCutoff: String): DataFrame = {
  val allPRs = events
    .filter(col("action") === "closed")
    .filter(col("is_merged") === true)
    .filter(col("merged_at") >= mergedSinceCutoff)

  val rapidashFilter =
    col("repo_name") === "itaipu" &&
      col("description").like("%Generated by Rapidash%")

  val warpPipeFilter =
    col("repo_name") === "itaipu" && (
      col("description").like("%Warp Pipe%") ||
        col("description").like("%WarpPipe%")
    ) && (
      col("title").like("%w/ Warp Pipe%") ||
        col("description").like("%Config object%") ||
        col("description").like("%productCustomerStatus%")
    )

  allPRs
    .filter(rapidashFilter || warpPipeFilter || col("repo_name") === "cross-segment-ai-tools")
    .withColumn(
      "ai_tool",
      when(col("repo_name") === "cross-segment-ai-tools", lit("cross-segment-ai-tools"))
        .when(col("description").like("%Generated by Rapidash%"), lit("Rapidash"))
        .otherwise(lit("Warp Pipe"))
    )
}

// COMMAND ----------

// MAGIC %md
// MAGIC ## 6. Code / analysis

// COMMAND ----------

// DBTITLE 1,Apply AI PR classification
val aiPRs = buildAiAssistedPullRequests(pullRequestEvents, mergedSince)

// COMMAND ----------

// DBTITLE 1,Estimated outputs and Rapidash parsing helpers
val typeCount = size(split(col("description"), "\\*\\*Type\\*\\*:")) - 1

val bulletCount =
  size(expr("filter(split(description, '\n'), x -> x rlike '^- \\\\*\\\\*[A-Z][a-zA-Z0-9]*\\\\*\\\\*')"))

val attributeCount = greatest(typeCount, bulletCount)

val withOutputs = aiPRs
  .withColumn(
    "estimated_outputs",
    when(col("ai_tool") === "cross-segment-ai-tools", lit(1))
      .when(col("ai_tool") === "Warp Pipe", lit(1))
      .when(attributeCount > 0, attributeCount)
      .otherwise(greatest(lit(1), col("changed_files") - 2))
  )

// COMMAND ----------

// DBTITLE 1,Monthly PR volume
val monthlyVolume = aiPRs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    countDistinct("author").alias("unique_authors"),
    sum("added_lines").alias("total_lines_added"),
    sum("deleted_lines").alias("total_lines_deleted"),
    sum("changed_files").alias("total_files_changed")
  )
  .orderBy(col("month").desc, col("ai_tool"))

// COMMAND ----------

// DBTITLE 1,Breakdown by author and month
val byAuthor = aiPRs
  .groupBy(
    date_trunc("month", col("merged_at")).alias("month"),
    col("ai_tool"),
    col("author")
  )
  .agg(
    countDistinct("pr_number").alias("prs_merged"),
    sum("added_lines").alias("lines_added"),
    sum("deleted_lines").alias("lines_deleted")
  )
  .orderBy(col("month").desc, col("prs_merged").desc)

// COMMAND ----------

// DBTITLE 1,Average time to merge
val timeToMerge = aiPRs
  .withColumn(
    "hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 1)
  )
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    round(avg("hours_to_merge"), 1).alias("avg_hours_to_merge"),
    min("hours_to_merge").alias("min_hours"),
    max("hours_to_merge").alias("max_hours"),
    countDistinct("pr_number").alias("total_prs")
  )
  .orderBy(col("month").desc, col("ai_tool"))

// COMMAND ----------

// DBTITLE 1,Individual PR list
val prList = aiPRs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .withColumn(
    "hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 0)
  )
  .select(
    col("month"),
    col("ai_tool"),
    col("repo_name"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("added_lines"),
    col("deleted_lines"),
    col("changed_files"),
    col("hours_to_merge"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

// COMMAND ----------

// DBTITLE 1,AI outputs per PR
val outputsPerPR = withOutputs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

// COMMAND ----------

// DBTITLE 1,Total AI outputs per month
val monthlyOutputs = withOutputs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    sum("estimated_outputs").alias("total_outputs"),
    round(avg("estimated_outputs"), 1).alias("avg_outputs_per_pr"),
    countDistinct("author").alias("unique_authors")
  )
  .orderBy(col("month").desc)

// COMMAND ----------

// DBTITLE 1,Cumulative total of AI-generated outputs
val cumulativeTotal = withOutputs
  .agg(
    sum("estimated_outputs").alias("total_outputs_to_date"),
    countDistinct("pr_number").alias("total_prs_to_date"),
    countDistinct("author").alias("unique_authors_to_date")
  )

// COMMAND ----------

// DBTITLE 1,PR content breakdown from description
val prContent = withOutputs
  .withColumn("attribute_type",
    regexp_extract(col("description"), "\\*\\*Type\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("owner_squad",
    regexp_extract(col("description"), "\\*\\*Owner\\*\\*:\\s*(?:Squad\\.)?([^\\n]+)", 1))
  .withColumn("domain",
    regexp_extract(col("description"), "\\*\\*Domain\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("context_summary",
    regexp_extract(col("description"), "###\\s*Context\\n+([^#\\n][^\\n]{0,200})", 1))
  .withColumn("output_description",
    regexp_extract(col("description"), "\\*\\*Output[:\\*]*\\s*([^\\n]{0,200})", 1))
  .withColumn("warp_pipe_product",
    regexp_extract(col("title"), "(?i)Add\\s+(.+?)\\s+(?:Activity|JM|Journey)", 1))
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("attribute_type"),
    col("owner_squad"),
    col("domain"),
    col("context_summary"),
    col("output_description"),
    col("warp_pipe_product"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 7. Validation

// COMMAND ----------

// DBTITLE 1,Check duplicate rows at repo and PR grain
val duplicateRepoPrKeys = aiPRs
  .groupBy("repo_name", "pr_number")
  .count()
  .filter(col("count") > 1)

val duplicateRepoPrKeyCount = duplicateRepoPrKeys.count()
println(s"Expected: zero duplicate keys at (repo_name, pr_number) grain -> found $duplicateRepoPrKeyCount")
require(duplicateRepoPrKeyCount == 0L, "Unexpected duplicate rows at repo_name + pr_number grain")

// COMMAND ----------

// DBTITLE 1,Compare pr_number-only vs composite distinct counts
val distinctPrNumberOnly = aiPRs.select("pr_number").distinct().count()
val distinctRepoAndPr = aiPRs.select("repo_name", "pr_number").distinct().count()

println(s"Distinct pr_number: $distinctPrNumberOnly")
println(s"Distinct (repo_name, pr_number): $distinctRepoAndPr")
println(
  "Expected: if these differ, pr_number is reused across repos and countDistinct(pr_number) metrics may be misleading"
)

// COMMAND ----------

// DBTITLE 1,Reconcile monthly volume with distinct PR population
val distinctAiPrCount = aiPRs.select("repo_name", "pr_number").distinct().count()
val sumMonthlyTotalPrs = monthlyVolume.agg(sum("total_prs").cast("long")).first().getLong(0)

println(s"Distinct PRs in aiPRs (repo + number): $distinctAiPrCount")
println(s"Sum of monthly total_prs across (month, ai_tool): $sumMonthlyTotalPrs")
println(
  "Expected: sums match when each PR falls in exactly one month and one ai_tool bucket (OKR safety check)"
)
require(
  distinctAiPrCount == sumMonthlyTotalPrs,
  s"Aggregation safety: distinct PRs $distinctAiPrCount != sum monthly total_prs $sumMonthlyTotalPrs"
)

// COMMAND ----------

// DBTITLE 1,Reconcile author breakdown totals per month and tool
val reconciledByAuthor = byAuthor
  .groupBy("month", "ai_tool")
  .agg(sum("prs_merged").cast("long").alias("sum_author_bucket_prs"))

val monthlyForJoin = monthlyVolume.select(
  col("month"),
  col("ai_tool"),
  col("total_prs").alias("monthly_total_prs")
)

val authorReconciliation = monthlyForJoin.join(reconciledByAuthor, Seq("month", "ai_tool"), "inner")

val authorMismatchCount = authorReconciliation
  .filter(col("monthly_total_prs") =!= col("sum_author_bucket_prs"))
  .count()

println(
  s"Expected: zero month and ai_tool groups where sum of author PR counts != monthly total_prs -> mismatches: $authorMismatchCount"
)
require(authorMismatchCount == 0L, "Author-level PR counts do not reconcile to monthly volume")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 8. Display and persistence

// COMMAND ----------

// DBTITLE 1,Persist and display monthly volume
monthlyVolume.write
  .format("delta")
  .mode("overwrite")
  .option("overwriteSchema", "true")
  .saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_volume_mensal")
display(monthlyVolume)

// COMMAND ----------

// DBTITLE 1,Persist and display breakdown by author
byAuthor.write
  .format("delta")
  .mode("overwrite")
  .option("overwriteSchema", "true")
  .saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_por_autor")
display(byAuthor)

// COMMAND ----------

// DBTITLE 1,Persist and display time to merge
timeToMerge.write
  .format("delta")
  .mode("overwrite")
  .option("overwriteSchema", "true")
  .saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_tempo_merge")
display(timeToMerge)

// COMMAND ----------

// DBTITLE 1,Persist and display PR list
prList.write
  .format("delta")
  .mode("overwrite")
  .option("overwriteSchema", "true")
  .saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_lista_prs")
display(prList)

// COMMAND ----------

// MAGIC %md
// MAGIC **Counting methodology (estimated outputs)**:
// MAGIC - New Rapidash PRs: counts occurrences of `**Type**:` in the description — each attribute has exactly one type declaration
// MAGIC - Update/migration PRs (no `**Type**:`): counts attribute bullets matching `- **PascalCaseName**`
// MAGIC - Fallback: `changed_files` as minimum estimate (1 file ≈ 1 output)
// MAGIC - `cross-segment-ai-tools` PRs: counted as 1 output per PR (tools/templates, not attributes)

// COMMAND ----------

// DBTITLE 1,Persist and display outputs per PR
outputsPerPR.write
  .format("delta")
  .mode("overwrite")
  .option("overwriteSchema", "true")
  .saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_por_pr")
display(outputsPerPR)

// COMMAND ----------

// DBTITLE 1,Display total AI outputs per month
// monthlyOutputs.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_mensais")
display(monthlyOutputs)

// COMMAND ----------

// DBTITLE 1,Persist and display cumulative totals
cumulativeTotal.write
  .format("delta")
  .mode("overwrite")
  .option("overwriteSchema", "true")
  .saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_total_acumulado")
display(cumulativeTotal)

// COMMAND ----------

// DBTITLE 1,Persist and display PR content breakdown
prContent.write
  .format("delta")
  .mode("overwrite")
  .option("overwriteSchema", "true")
  .saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_pr_content")
display(prContent)
