// Databricks notebook source
// MAGIC %md
// MAGIC # AI-Assisted PRs Monitor
// MAGIC
// MAGIC **Context**: This notebook supports monthly OKR reporting on pull requests created with AI assistance in the `itaipu` (Rapidash / Warp Pipe) and `cross-segment-ai-tools` repositories.
// MAGIC
// MAGIC **Objective**: Quantify merged AI-assisted PR volume, authors, timing, estimated outputs, and structured fields from descriptions for leadership dashboards.
// MAGIC
// MAGIC **Method**:
// MAGIC 1. Load merged PR events from the canonical Ist dataset and apply scope filters (closed, merged, cutoff date).
// MAGIC 2. Classify PRs into `Rapidash`, `Warp Pipe`, or `cross-segment-ai-tools` using repository and description/title rules.
// MAGIC 3. Build monthly aggregates, author breakdowns, merge-time metrics, output estimates, cumulative totals, and content extractions.
// MAGIC 4. Validate grain, required columns, and reconciliation before materializing outputs.
// MAGIC 5. Overwrite Delta output tables and display results for QA.
// MAGIC
// MAGIC **Analysis structure**:
// MAGIC - 1. Imports
// MAGIC - 2. Data sources
// MAGIC - 3. Widgets
// MAGIC - 4. Variable filters
// MAGIC - 5. Functions
// MAGIC - 6. Code / analysis
// MAGIC - 7. Validation
// MAGIC - 8. Display
// MAGIC
// MAGIC **Data sources**:
// MAGIC - `etl.ist__dataset.pull_request_events` — event-level PR data (closed, merged PRs in scope); used as the single base for all metrics and output tables.
// MAGIC
// MAGIC **Main assumptions**:
// MAGIC - `merged_at >= 2025-01-01` defines the reporting window; filters `action === closed` and `is_merged === true` match the intended population.
// MAGIC - Rapidash vs Warp Pipe vs cross-segment classification follows the inline string rules; any change to product wording affects counts.
// MAGIC - Estimated AI outputs use description heuristics (`**Type**:`, bullet patterns, or `changed_files` fallback) and are approximate, not audited ground truth.
// MAGIC - Monthly aggregates use `countDistinct("pr_number")` as in the source notebook; PR numbers could collide across repositories if the upstream key is not globally unique.

// COMMAND ----------

// MAGIC %md
// MAGIC ## 1. Imports

// COMMAND ----------

// DBTITLE 1,Spark SQL imports
import org.apache.spark.sql.functions._

// COMMAND ----------

// MAGIC %md
// MAGIC ## 2. Data sources

// COMMAND ----------

// DBTITLE 1,Load pull request events
val pullRequestEventsBase = spark.table("etl.ist__dataset.pull_request_events")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 3. Widgets
// MAGIC
// MAGIC No runtime widgets; date cutoff and filters are fixed in code (section 4).

// COMMAND ----------

// MAGIC %md
// MAGIC ## 4. Variable filters

// COMMAND ----------

// DBTITLE 1,Filter closed merged PRs since cutoff date
val allPRs = pullRequestEventsBase
  .filter(col("action") === "closed")
  .filter(col("is_merged") === true)
  .filter(col("merged_at") >= "2025-01-01")

// COMMAND ----------

// DBTITLE 1,Define Rapidash and Warp Pipe classification rules
// Rapidash: explicit signature "Generated by Rapidash" in the description
val rapidashFilter =
  col("repo_name") === "itaipu" &&
  col("description").like("%Generated by Rapidash%")

// Warp Pipe: PRs that effectively create products (JM + Activity + Eligibility + Conversion)
// Excludes infra/cleanup PRs that only mention Warp Pipe
val warpPipeFilter =
  col("repo_name") === "itaipu" && (
    col("description").like("%Warp Pipe%") ||
    col("description").like("%WarpPipe%")
  ) && (
    col("title").like("%w/ Warp Pipe%") ||
    col("description").like("%Config object%") ||
    col("description").like("%productCustomerStatus%")
  )

// COMMAND ----------

// DBTITLE 1,Build AI-assisted PRs with tool label
val aiPRs = allPRs
  .filter(rapidashFilter || warpPipeFilter || col("repo_name") === "cross-segment-ai-tools")
  .withColumn("ai_tool",
    when(col("repo_name") === "cross-segment-ai-tools", lit("cross-segment-ai-tools"))
    .when(col("description").like("%Generated by Rapidash%"), lit("Rapidash"))
    .otherwise(lit("Warp Pipe"))
  )

// COMMAND ----------

// MAGIC %md
// MAGIC ## 5. Functions
// MAGIC
// MAGIC No shared helper functions; transformations are inlined in the analysis section.

// COMMAND ----------

// MAGIC %md
// MAGIC ## 6. Code / analysis

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.1 Monthly PR volume

// COMMAND ----------

// DBTITLE 1,Aggregate monthly PR volume by AI tool
val monthlyVolume = aiPRs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    countDistinct("author").alias("unique_authors"),
    sum("added_lines").alias("total_lines_added"),
    sum("deleted_lines").alias("total_lines_deleted"),
    sum("changed_files").alias("total_files_changed")
  )
  .orderBy(col("month").desc, col("ai_tool"))

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.2 Breakdown by author and month

// COMMAND ----------

// DBTITLE 1,Aggregate PR metrics by month tool and author
val byAuthor = aiPRs
  .groupBy(
    date_trunc("month", col("merged_at")).alias("month"),
    col("ai_tool"),
    col("author")
  )
  .agg(
    countDistinct("pr_number").alias("prs_merged"),
    sum("added_lines").alias("lines_added"),
    sum("deleted_lines").alias("lines_deleted")
  )
  .orderBy(col("month").desc, col("prs_merged").desc)

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.3 Average time to merge (hours)

// COMMAND ----------

// DBTITLE 1,Compute merge duration statistics by month and tool
val timeToMerge = aiPRs
  .withColumn("hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 1)
  )
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    round(avg("hours_to_merge"), 1).alias("avg_hours_to_merge"),
    min("hours_to_merge").alias("min_hours"),
    max("hours_to_merge").alias("max_hours"),
    countDistinct("pr_number").alias("total_prs")
  )
  .orderBy(col("month").desc, col("ai_tool"))

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.4 Individual PR list

// COMMAND ----------

// DBTITLE 1,Build ordered PR list with merge timing
val prList = aiPRs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .withColumn("hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 0)
  )
  .select(
    col("month"),
    col("ai_tool"),
    col("repo_name"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("added_lines"),
    col("deleted_lines"),
    col("changed_files"),
    col("hours_to_merge"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.5 AI outputs per PR (estimated attributes)
// MAGIC
// MAGIC **Counting methodology:**
// MAGIC - New Rapidash PRs: counts occurrences of `**Type**:` in the description — each attribute has exactly one type declaration
// MAGIC - Update/migration PRs (no `**Type**:`): counts attribute bullets matching `- **PascalCaseName**`
// MAGIC - Fallback: `changed_files` as minimum estimate (1 file ≈ 1 output)
// MAGIC - `cross-segment-ai-tools` PRs: counted as 1 output per PR (tools/templates, not attributes)

// COMMAND ----------

// DBTITLE 1,Estimate outputs per PR from description heuristics
val typeCount = size(split(col("description"), "\\*\\*Type\\*\\*:")) - 1

val bulletCount = size(expr("filter(split(description, '\n'), x -> x rlike '^- \\\\*\\\\*[A-Z][a-zA-Z0-9]*\\\\*\\\\*')"))

val attributeCount = greatest(typeCount, bulletCount)

val withOutputs = aiPRs
  .withColumn("estimated_outputs",
    when(col("ai_tool") === "cross-segment-ai-tools", lit(1))
    .when(col("ai_tool") === "Warp Pipe", lit(1))
    .when(attributeCount > 0, attributeCount)
    .otherwise(greatest(lit(1), col("changed_files") - 2))
  )

// COMMAND ----------

// DBTITLE 1,Select outputs-per-PR detail columns
val outputsPerPR = withOutputs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.6 Total AI outputs per month

// COMMAND ----------

// DBTITLE 1,Aggregate estimated outputs by month
val monthlyOutputs = withOutputs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    sum("estimated_outputs").alias("total_outputs"),
    round(avg("estimated_outputs"), 1).alias("avg_outputs_per_pr"),
    countDistinct("author").alias("unique_authors")
  )
  .orderBy(col("month").desc)

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.7 Cumulative total of AI-generated outputs

// COMMAND ----------

// DBTITLE 1,Compute cumulative outputs and PR counts
val cumulativeTotal = withOutputs
  .agg(
    sum("estimated_outputs").alias("total_outputs_to_date"),
    countDistinct("pr_number").alias("total_prs_to_date"),
    countDistinct("author").alias("unique_authors_to_date")
  )

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.8 PR content breakdown (extracted from description)
// MAGIC
// MAGIC Extracts structured fields from Rapidash PR descriptions for detailed reporting.

// COMMAND ----------

// DBTITLE 1,Extract Rapidash and Warp Pipe fields from text
val prContent = withOutputs
  // Rapidash standard fields
  .withColumn("attribute_type",
    regexp_extract(col("description"), "\\*\\*Type\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("owner_squad",
    regexp_extract(col("description"), "\\*\\*Owner\\*\\*:\\s*(?:Squad\\.)?([^\\n]+)", 1))
  .withColumn("domain",
    regexp_extract(col("description"), "\\*\\*Domain\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("context_summary",
    regexp_extract(col("description"), "###\\s*Context\\n+([^#\\n][^\\n]{0,200})", 1))
  .withColumn("output_description",
    regexp_extract(col("description"), "\\*\\*Output[:\\*]*\\s*([^\\n]{0,200})", 1))
  // Warp Pipe: extract product name from title (e.g. "Add X Activity, Eligibility... w/ Warp Pipe")
  .withColumn("warp_pipe_product",
    regexp_extract(col("title"), "(?i)Add\\s+(.+?)\\s+(?:Activity|JM|Journey)", 1))
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("attribute_type"),
    col("owner_squad"),
    col("domain"),
    col("context_summary"),
    col("output_description"),
    col("warp_pipe_product"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 7. Validation

// COMMAND ----------

// DBTITLE 1,Check required columns after read
val requiredPrEventColumns = Seq(
  "action",
  "is_merged",
  "merged_at",
  "repo_name",
  "description",
  "title",
  "pr_number",
  "author",
  "added_lines",
  "deleted_lines",
  "changed_files",
  "created_at"
)
val missingAfterRead = requiredPrEventColumns.filterNot(pullRequestEventsBase.columns.contains)
require(missingAfterRead.isEmpty, s"Missing columns on pull_request_events: ${missingAfterRead.mkString(", ")}")

// COMMAND ----------

// DBTITLE 1,Check event grain versus PR key for AI population
val aiPrRowCount = aiPRs.count()
val aiPrDistinctKeys = aiPRs.select("repo_name", "pr_number").distinct().count()
println(s"aiPRs rows: $aiPrRowCount, distinct (repo_name, pr_number): $aiPrDistinctKeys")
if (aiPrRowCount != aiPrDistinctKeys) {
  println("Warning: multiple event rows per (repo_name, pr_number); downstream distinct counts follow source logic.")
}

// COMMAND ----------

// DBTITLE 1,Check null timestamps used in merge-duration metrics
val nullMergedAt = aiPRs.filter(col("merged_at").isNull).count()
val nullCreatedAt = aiPRs.filter(col("created_at").isNull).count()
require(nullMergedAt == 0L && nullCreatedAt == 0L,
  s"Null timestamps would break time-to-merge (merged_at=$nullMergedAt, created_at=$nullCreatedAt)")

// COMMAND ----------

// DBTITLE 1,Reconcile monthly bucket totals with global PR distinct count
val sumMonthlyDistinctPrs = monthlyVolume.agg(sum("total_prs").as("s")).collect()(0).getLong(0)
val globalDistinctPrNumber = aiPRs.agg(countDistinct("pr_number").as("c")).collect()(0).getLong(0)
println(s"Sum of monthlyVolume total_prs across buckets: $sumMonthlyDistinctPrs")
println(s"Global countDistinct(pr_number) on aiPRs: $globalDistinctPrNumber")
if (sumMonthlyDistinctPrs != globalDistinctPrNumber) {
  println("Warning: monthly sum does not match global countDistinct(pr_number); possible cross-repo pr_number collision or grain mismatch.")
}

// COMMAND ----------

// MAGIC %md
// MAGIC ## 8. Display

// COMMAND ----------

// DBTITLE 1,Write and display monthly PR volume
monthlyVolume.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_volume_mensal")
display(monthlyVolume)

// COMMAND ----------

// DBTITLE 1,Write and display author breakdown
byAuthor.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_por_autor")
display(byAuthor)

// COMMAND ----------

// DBTITLE 1,Write and display merge time metrics
timeToMerge.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_tempo_merge")
display(timeToMerge)

// COMMAND ----------

// DBTITLE 1,Write and display PR list
prList.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_lista_prs")
display(prList)

// COMMAND ----------

// DBTITLE 1,Write and display outputs per PR
outputsPerPR.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_por_pr")
display(outputsPerPR)

// COMMAND ----------

// DBTITLE 1,Display monthly outputs (table write commented in source)
// monthlyOutputs.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_mensais")
display(monthlyOutputs)

// COMMAND ----------

// DBTITLE 1,Write and display cumulative totals
cumulativeTotal.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_total_acumulado")
display(cumulativeTotal)

// COMMAND ----------

// DBTITLE 1,Write and display PR content extraction
prContent.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_pr_content")
display(prContent)
