// Databricks notebook source
// MAGIC %md
// MAGIC # AI-Assisted PRs Monitor (Itaipu & cross-segment-ai-tools)
// MAGIC
// MAGIC **Context**: This notebook supports monthly OKR reporting on merged pull requests that used AI-assisted workflows in the `itaipu` repository (Rapidash and Warp Pipe patterns) and all merged PRs in `cross-segment-ai-tools`.
// MAGIC
// MAGIC **Objective**: Produce recurring aggregates and detail tables for AI-assisted PR volume, authors, time-to-merge, estimated outputs, and extracted PR description fields—aligned with the preserved business rules and output table names.
// MAGIC
// MAGIC **Method**:
// MAGIC 1. Read merged, closed PR events from the canonical events table and apply the agreed date and repository filters.
// MAGIC 2. Classify each row into an `ai_tool` (Rapidash, Warp Pipe, or cross-segment-ai-tools).
// MAGIC 3. Build monthly and PR-level metrics, write to Delta tables under `usr.br__customer_lifecycle_optimization`, and display results.
// MAGIC 4. Run sanity checks (no joins in this pipeline; filter impact, columns, grain, aggregation safety).
// MAGIC
// MAGIC **Analysis structure**:
// MAGIC - 0. Intro / README (this block)
// MAGIC - 1. Imports
// MAGIC - 2. Data sources
// MAGIC - 3. Widgets
// MAGIC - 4. Variable filters
// MAGIC - 5. Functions
// MAGIC - 6. Code / analysis
// MAGIC - 7. Validation
// MAGIC - 8. Display
// MAGIC
// MAGIC **Data sources**:
// MAGIC - `etl.ist__dataset.pull_request_events` — single base dataset; one row per PR event; supports filters on `action`, `is_merged`, `merged_at`, `repo_name`, `description`, and `title`.
// MAGIC
// MAGIC **Main assumptions**:
// MAGIC - Merged PRs are identified with `action === "closed"` and `is_merged === true` (preserved from the source notebook).
// MAGIC - Rapidash PRs in `itaipu` are detected via `description` containing `Generated by Rapidash`.
// MAGIC - Warp Pipe PRs use the original composite filter on `title` / `description` (excluding infra-only mentions).
// MAGIC - All merged PRs in `cross-segment-ai-tools` are in scope with `ai_tool` fixed to that repo name.
// MAGIC - Estimated output counts for Rapidash follow the documented heuristics (`**Type**:`, bullet patterns, or fallback vs `changed_files`).

// COMMAND ----------

// MAGIC %md
// MAGIC ## 1. Imports

// COMMAND ----------

// DBTITLE 1,Imports
import org.apache.spark.sql.DataFrame
import org.apache.spark.sql.functions._

// COMMAND ----------

// MAGIC %md
// MAGIC ## 2. Data sources

// COMMAND ----------

// DBTITLE 1,Load pull request events base
val pullRequestEvents: DataFrame = spark.table("etl.ist__dataset.pull_request_events")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 3. Widgets

// COMMAND ----------

// DBTITLE 1,Create merged-at cutoff widget
dbutils.widgets.text("mergedAtCutoff", "2025-01-01")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 4. Variable filters

// COMMAND ----------

// DBTITLE 1,Define cutoff and merged-PR scope
val mergedAtCutoff: String = dbutils.widgets.get("mergedAtCutoff")

val allPRs: DataFrame = pullRequestEvents
  .filter(col("action") === "closed")
  .filter(col("is_merged") === true)
  .filter(col("merged_at") >= mergedAtCutoff)

// Rapidash: explicit signature "Generated by Rapidash" in the description
val rapidashFilter =
  col("repo_name") === "itaipu" &&
  col("description").like("%Generated by Rapidash%")

// Warp Pipe: PRs that effectively create products (JM + Activity + Eligibility + Conversion)
// Excludes infra/cleanup PRs that only mention Warp Pipe
val warpPipeFilter =
  col("repo_name") === "itaipu" && (
    col("description").like("%Warp Pipe%") ||
    col("description").like("%WarpPipe%")
  ) && (
    col("title").like("%w/ Warp Pipe%") ||
    col("description").like("%Config object%") ||
    col("description").like("%productCustomerStatus%")
  )

val aiPRs: DataFrame = allPRs
  .filter(rapidashFilter || warpPipeFilter || col("repo_name") === "cross-segment-ai-tools")
  .withColumn(
    "ai_tool",
    when(col("repo_name") === "cross-segment-ai-tools", lit("cross-segment-ai-tools"))
      .when(col("description").like("%Generated by Rapidash%"), lit("Rapidash"))
      .otherwise(lit("Warp Pipe"))
  )

// COMMAND ----------

// MAGIC %md
// MAGIC ## 5. Functions

// COMMAND ----------

// DBTITLE 1,Heuristics for estimated Rapidash outputs
def typeDeclarationCount(descriptionColumn: org.apache.spark.sql.Column): org.apache.spark.sql.Column =
  size(split(descriptionColumn, "\\*\\*Type\\*\\*:")) - 1

def attributeBulletCount(descriptionColumn: org.apache.spark.sql.Column): org.apache.spark.sql.Column =
  size(expr("filter(split(description, '\n'), x -> x rlike '^- \\\\*\\\\*[A-Z][a-zA-Z0-9]*\\\\*\\\\*')"))

def withEstimatedOutputs(baseAiPrs: DataFrame): DataFrame = {
  val typeCnt = typeDeclarationCount(col("description"))
  val bulletCnt = attributeBulletCount(col("description"))
  val attributeCnt = greatest(typeCnt, bulletCnt)

  baseAiPrs
    .withColumn(
      "estimated_outputs",
      when(col("ai_tool") === "cross-segment-ai-tools", lit(1))
        .when(col("ai_tool") === "Warp Pipe", lit(1))
        .when(attributeCnt > 0, attributeCnt)
        .otherwise(greatest(lit(1), col("changed_files") - 2))
    )
}

// COMMAND ----------

// MAGIC %md
// MAGIC ## 6. Code / analysis

// COMMAND ----------

// DBTITLE 1,Add hours to merge and estimated outputs
val aiPRsWithHours: DataFrame = aiPRs
  .withColumn(
    "hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 1)
  )

val withOutputs: DataFrame = withEstimatedOutputs(aiPRs)

// COMMAND ----------

// DBTITLE 1,Monthly PR volume
val monthlyVolume: DataFrame = aiPRs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    countDistinct("author").alias("unique_authors"),
    sum("added_lines").alias("total_lines_added"),
    sum("deleted_lines").alias("total_lines_deleted"),
    sum("changed_files").alias("total_files_changed")
  )
  .orderBy(col("month").desc, col("ai_tool"))

monthlyVolume.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_volume_mensal"
)

// COMMAND ----------

// DBTITLE 1,Breakdown by author and month
val byAuthor: DataFrame = aiPRs
  .groupBy(
    date_trunc("month", col("merged_at")).alias("month"),
    col("ai_tool"),
    col("author")
  )
  .agg(
    countDistinct("pr_number").alias("prs_merged"),
    sum("added_lines").alias("lines_added"),
    sum("deleted_lines").alias("lines_deleted")
  )
  .orderBy(col("month").desc, col("prs_merged").desc)

byAuthor.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_por_autor"
)

// COMMAND ----------

// DBTITLE 1,Average time to merge (hours)
val timeToMerge: DataFrame = aiPRsWithHours
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    round(avg("hours_to_merge"), 1).alias("avg_hours_to_merge"),
    min("hours_to_merge").alias("min_hours"),
    max("hours_to_merge").alias("max_hours"),
    countDistinct("pr_number").alias("total_prs")
  )
  .orderBy(col("month").desc, col("ai_tool"))

timeToMerge.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_tempo_merge"
)

// COMMAND ----------

// DBTITLE 1,Individual PR list
val prList: DataFrame = aiPRs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .withColumn(
    "hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 0)
  )
  .select(
    col("month"),
    col("ai_tool"),
    col("repo_name"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("added_lines"),
    col("deleted_lines"),
    col("changed_files"),
    col("hours_to_merge"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

prList.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_lista_prs"
)

// COMMAND ----------

// DBTITLE 1,AI outputs per PR (estimated attributes)
// Counting methodology (unchanged):
// - New Rapidash PRs: counts occurrences of `**Type**:` in the description — each attribute has exactly one type declaration
// - Update/migration PRs (no `**Type**:`): counts attribute bullets matching `- **PascalCaseName**`
// - Fallback: `changed_files` as minimum estimate (1 file ≈ 1 output)
// - `cross-segment-ai-tools` PRs: counted as 1 output per PR (tools/templates, not attributes)

val outputsPerPR: DataFrame = withOutputs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

outputsPerPR.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_outputs_por_pr"
)

// COMMAND ----------

// DBTITLE 1,Total AI outputs per month
val monthlyOutputs: DataFrame = withOutputs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    sum("estimated_outputs").alias("total_outputs"),
    round(avg("estimated_outputs"), 1).alias("avg_outputs_per_pr"),
    countDistinct("author").alias("unique_authors")
  )
  .orderBy(col("month").desc)

// Preserved: monthly outputs table write remains commented in the source notebook.
// monthlyOutputs.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_mensais")

// COMMAND ----------

// DBTITLE 1,Cumulative total of AI-generated outputs
val cumulativeTotal: DataFrame = withOutputs
  .agg(
    sum("estimated_outputs").alias("total_outputs_to_date"),
    countDistinct("pr_number").alias("total_prs_to_date"),
    countDistinct("author").alias("unique_authors_to_date")
  )

cumulativeTotal.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_total_acumulado"
)

// COMMAND ----------

// DBTITLE 1,PR content breakdown (extracted from description)
val prContent: DataFrame = withOutputs
  .withColumn("attribute_type", regexp_extract(col("description"), "\\*\\*Type\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("owner_squad", regexp_extract(col("description"), "\\*\\*Owner\\*\\*:\\s*(?:Squad\\.)?([^\\n]+)", 1))
  .withColumn("domain", regexp_extract(col("description"), "\\*\\*Domain\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("context_summary", regexp_extract(col("description"), "###\\s*Context\\n+([^#\\n][^\\n]{0,200})", 1))
  .withColumn("output_description", regexp_extract(col("description"), "\\*\\*Output[:\\*]*\\s*([^\\n]{0,200})", 1))
  .withColumn("warp_pipe_product", regexp_extract(col("title"), "(?i)Add\\s+(.+?)\\s+(?:Activity|JM|Journey)", 1))
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("attribute_type"),
    col("owner_squad"),
    col("domain"),
    col("context_summary"),
    col("output_description"),
    col("warp_pipe_product"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

prContent.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable(
  "usr.br__customer_lifecycle_optimization.ai_monitor_pr_content"
)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 7. Validation
// MAGIC
// MAGIC This notebook **does not join** the PR events table to any other dataset. Checks below focus on filter impact, required columns, PR-level grain, and aggregation safety instead of join coverage.

// COMMAND ----------

// DBTITLE 1,Confirm no joins and state validation focus
println(
  "Validation scope: no joins — verifying filters, required columns, duplicates at (repo_name, pr_number), merged_at bounds, and row vs PR grain."
)

// COMMAND ----------

// DBTITLE 1,Check required columns after read
val requiredColumns = Seq(
  "action",
  "is_merged",
  "merged_at",
  "repo_name",
  "description",
  "title",
  "pr_number",
  "author",
  "added_lines",
  "deleted_lines",
  "changed_files",
  "created_at"
)

val missingColumns = requiredColumns.filterNot(pullRequestEvents.columns.contains)
println(s"Expected: zero missing required columns -> ${requiredColumns.mkString(", ")}")
require(missingColumns.isEmpty, s"Missing columns: ${missingColumns.mkString(", ")}")

// COMMAND ----------

// DBTITLE 1,Validate filter impact on row counts (stepwise)
val afterClosed = pullRequestEvents.filter(col("action") === "closed")
val afterMergedFlag = afterClosed.filter(col("is_merged") === true)
val afterMergedAt = afterMergedFlag.filter(col("merged_at") >= mergedAtCutoff)

val countAfterClosed = afterClosed.count()
val countAfterMerged = afterMergedFlag.count()
val countAllPRs = afterMergedAt.count()
val countAiPRs = aiPRs.count()

println(s"Rows after closed filter: $countAfterClosed")
println(s"Rows after is_merged = true: $countAfterMerged")
println(s"Rows after merged_at >= $mergedAtCutoff (allPRs scope): $countAllPRs")
println(s"Rows after AI scope filters (aiPRs): $countAiPRs")
println("Expected: each step should monotonically decrease or stay equal; large unexpected drops warrant reviewing event grain and filters.")

// COMMAND ----------

// DBTITLE 1,Check merged_at min and max after scope filters
val mergedAtBounds = allPRs.agg(min("merged_at").alias("min_merged_at"), max("merged_at").alias("max_merged_at"))
display(mergedAtBounds)
println(s"Expected: min merged_at is on or after $mergedAtCutoff for allPRs")

// COMMAND ----------

// DBTITLE 1,Check nulls in merged_at for scoped PRs
val nullMergedAt = allPRs.filter(col("merged_at").isNull).count()
println(s"Rows with null merged_at in allPRs: $nullMergedAt")
println("Expected: zero null merged_at rows after merged_at filter (otherwise investigate source data)")

// COMMAND ----------

// DBTITLE 1,Check duplicates at repo and PR number grain
val duplicatePrKeys = aiPRs
  .groupBy("repo_name", "pr_number")
  .count()
  .filter(col("count") > 1)

display(duplicatePrKeys)
println("Expected: zero duplicate rows per (repo_name, pr_number) in aiPRs; duplicates would inflate sums and distinct counts.")

// COMMAND ----------

// DBTITLE 1,Validate row count vs distinct PR keys (aggregation safety)
val grainCheck = aiPRs.agg(
  count(lit(1)).alias("row_count"),
  countDistinct(col("repo_name"), col("pr_number")).alias("distinct_repo_pr")
)

display(grainCheck)
println("Expected: row_count equals distinct_repo_pr if each PR appears once at this grain.")

// COMMAND ----------

// DBTITLE 1,Cross-check PR distinct counts vs list output grain
val distinctPrsAi = aiPRs.select("repo_name", "pr_number").distinct().count()
val rowsPrList = prList.select("repo_name", "pr_number").distinct().count()
println(s"Distinct (repo_name, pr_number) in aiPRs: $distinctPrsAi")
println(s"Distinct (repo_name, pr_number) in prList: $rowsPrList")
println("Expected: prList should align with aiPRs PR keys (same PR set).")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 8. Display

// COMMAND ----------

// DBTITLE 1,Display monthly volume
display(monthlyVolume)

// COMMAND ----------

// DBTITLE 1,Display breakdown by author
display(byAuthor)

// COMMAND ----------

// DBTITLE 1,Display time to merge metrics
display(timeToMerge)

// COMMAND ----------

// DBTITLE 1,Display PR list
display(prList)

// COMMAND ----------

// DBTITLE 1,Display outputs per PR
display(outputsPerPR)

// COMMAND ----------

// DBTITLE 1,Display monthly outputs (table write intentionally commented)
display(monthlyOutputs)

// COMMAND ----------

// DBTITLE 1,Display cumulative totals
display(cumulativeTotal)

// COMMAND ----------

// DBTITLE 1,Display PR content breakdown
display(prContent)
