// Databricks notebook source
// MAGIC %md
// MAGIC # AI-Assisted PRs Monitor
// MAGIC
// MAGIC **Context**: This notebook supports monthly OKR reporting on AI-assisted pull request activity in engineering repositories.
// MAGIC
// MAGIC **Objective**: Measure monthly AI-assisted PR volume, author activity, time to merge, estimated outputs, and content breakdown for reporting.
// MAGIC
// MAGIC **Method**:
// MAGIC 1. Read merged closed PR events from a single source table (no joins).
// MAGIC 2. Classify PRs by tool (Rapidash, Warp Pipe, cross-segment-ai-tools) using preserved filter logic.
// MAGIC 3. Build monthly and cumulative aggregates and Delta output tables.
// MAGIC 4. Validate required columns, date scope, repo scope, PR grain, duplicate-row risk, and aggregation consistency.
// MAGIC 5. Display the same result sets as the operational notebook.
// MAGIC
// MAGIC **Analysis structure**:
// MAGIC - 0. Intro / README (this block)
// MAGIC - 1. Imports
// MAGIC - 2. Data sources
// MAGIC - 3. Widgets
// MAGIC - 4. Variable filters
// MAGIC - 5. Functions
// MAGIC - 6. Code / analysis
// MAGIC - 7. Validation
// MAGIC - 8. Display
// MAGIC
// MAGIC **Data sources**:
// MAGIC - `etl.ist__dataset.pull_request_events` — single source of PR events; grain is one row per event row in the table (validated against PR key); no joins in this pipeline.
// MAGIC
// MAGIC **Main assumptions**:
// MAGIC - `countDistinct("pr_number")` is the intended PR cardinality metric; sums of line/file metrics assume at most one analytic row per `(repo_name, pr_number)` in `aiPRs` (validated below).
// MAGIC - Lower bound `merged_at >= "2025-01-01"` and repository filters are fixed scope for this OKR slice.

// COMMAND ----------

// MAGIC %md
// MAGIC ## 1. Imports

// COMMAND ----------

// DBTITLE 1,Imports
import org.apache.spark.sql.functions._

// COMMAND ----------

// MAGIC %md
// MAGIC ## 2. Data sources

// COMMAND ----------

// DBTITLE 1,Load pull request events
val pullRequestEventsSource = spark.table("etl.ist__dataset.pull_request_events")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 3. Widgets

// COMMAND ----------

// MAGIC %md
// MAGIC No runtime widgets in this notebook; date lower bound and repo filters are fixed in **Variable filters** to match the current OKR scope.

// COMMAND ----------

// MAGIC %md
// MAGIC ## 4. Variable filters

// COMMAND ----------

// DBTITLE 1,Filter merged closed PRs and build AI classification
val allPRs = pullRequestEventsSource
  .filter(col("action") === "closed")
  .filter(col("is_merged") === true)
  .filter(col("merged_at") >= "2025-01-01")

// Rapidash: explicit signature "Generated by Rapidash" in the description
val rapidashFilter =
  col("repo_name") === "itaipu" &&
  col("description").like("%Generated by Rapidash%")

// Warp Pipe: PRs that effectively create products (JM + Activity + Eligibility + Conversion)
// Excludes infra/cleanup PRs that only mention Warp Pipe
val warpPipeFilter =
  col("repo_name") === "itaipu" && (
    col("description").like("%Warp Pipe%") ||
    col("description").like("%WarpPipe%")
  ) && (
    col("title").like("%w/ Warp Pipe%") ||
    col("description").like("%Config object%") ||
    col("description").like("%productCustomerStatus%")
  )

val aiPRs = allPRs
  .filter(rapidashFilter || warpPipeFilter || col("repo_name") === "cross-segment-ai-tools")
  .withColumn("ai_tool",
    when(col("repo_name") === "cross-segment-ai-tools", lit("cross-segment-ai-tools"))
    .when(col("description").like("%Generated by Rapidash%"), lit("Rapidash"))
    .otherwise(lit("Warp Pipe"))
  )

// COMMAND ----------

// MAGIC %md
// MAGIC ## 5. Functions

// COMMAND ----------

// MAGIC %md
// MAGIC No shared helper functions; classification filters and expressions are kept inline to preserve the original logic.

// COMMAND ----------

// MAGIC %md
// MAGIC ## 6. Code / analysis

// COMMAND ----------

// DBTITLE 1,Monthly PR volume
val monthlyVolume = aiPRs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    countDistinct("author").alias("unique_authors"),
    sum("added_lines").alias("total_lines_added"),
    sum("deleted_lines").alias("total_lines_deleted"),
    sum("changed_files").alias("total_files_changed")
  )
  .orderBy(col("month").desc, col("ai_tool"))

monthlyVolume.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_volume_mensal")

// COMMAND ----------

// DBTITLE 1,Breakdown by author and month
val byAuthor = aiPRs
  .groupBy(
    date_trunc("month", col("merged_at")).alias("month"),
    col("ai_tool"),
    col("author")
  )
  .agg(
    countDistinct("pr_number").alias("prs_merged"),
    sum("added_lines").alias("lines_added"),
    sum("deleted_lines").alias("lines_deleted")
  )
  .orderBy(col("month").desc, col("prs_merged").desc)

byAuthor.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_por_autor")

// COMMAND ----------

// DBTITLE 1,Average time to merge
val timeToMerge = aiPRs
  .withColumn("hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 1)
  )
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    round(avg("hours_to_merge"), 1).alias("avg_hours_to_merge"),
    min("hours_to_merge").alias("min_hours"),
    max("hours_to_merge").alias("max_hours"),
    countDistinct("pr_number").alias("total_prs")
  )
  .orderBy(col("month").desc, col("ai_tool"))

timeToMerge.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_tempo_merge")

// COMMAND ----------

// DBTITLE 1,Individual PR list
val prList = aiPRs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .withColumn("hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 0)
  )
  .select(
    col("month"),
    col("ai_tool"),
    col("repo_name"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("added_lines"),
    col("deleted_lines"),
    col("changed_files"),
    col("hours_to_merge"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

prList.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_lista_prs")

// COMMAND ----------

// MAGIC %md
// MAGIC **Estimated outputs — counting methodology** (preserved):
// MAGIC - New Rapidash PRs: counts occurrences of `**Type**:` in the description — each attribute has exactly one type declaration
// MAGIC - Update/migration PRs (no `**Type**:`): counts attribute bullets matching `- **PascalCaseName**`
// MAGIC - Fallback: `changed_files` as minimum estimate (1 file ≈ 1 output)
// MAGIC - `cross-segment-ai-tools` PRs: counted as 1 output per PR (tools/templates, not attributes)

// COMMAND ----------

// DBTITLE 1,Build estimated outputs column
val typeCount = size(split(col("description"), "\\*\\*Type\\*\\*:")) - 1

val bulletCount = size(expr("filter(split(description, '\n'), x -> x rlike '^- \\\\*\\\\*[A-Z][a-zA-Z0-9]*\\\\*\\\\*')"))

val attributeCount = greatest(typeCount, bulletCount)

val withOutputs = aiPRs
  .withColumn("estimated_outputs",
    when(col("ai_tool") === "cross-segment-ai-tools", lit(1))
    .when(col("ai_tool") === "Warp Pipe", lit(1))
    .when(attributeCount > 0, attributeCount)
    .otherwise(greatest(lit(1), col("changed_files") - 2))
  )

val outputsPerPR = withOutputs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

outputsPerPR.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_por_pr")

// COMMAND ----------

// DBTITLE 1,Total AI outputs per month
val monthlyOutputs = withOutputs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    sum("estimated_outputs").alias("total_outputs"),
    round(avg("estimated_outputs"), 1).alias("avg_outputs_per_pr"),
    countDistinct("author").alias("unique_authors")
  )
  .orderBy(col("month").desc)

// monthlyOutputs.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_mensais")

// COMMAND ----------

// DBTITLE 1,Cumulative total of AI-generated outputs
val cumulativeTotal = withOutputs
  .agg(
    sum("estimated_outputs").alias("total_outputs_to_date"),
    countDistinct("pr_number").alias("total_prs_to_date"),
    countDistinct("author").alias("unique_authors_to_date")
  )

cumulativeTotal.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_total_acumulado")

// COMMAND ----------

// DBTITLE 1,PR content breakdown from description
val prContent = withOutputs
  .withColumn("attribute_type",
    regexp_extract(col("description"), "\\*\\*Type\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("owner_squad",
    regexp_extract(col("description"), "\\*\\*Owner\\*\\*:\\s*(?:Squad\\.)?([^\\n]+)", 1))
  .withColumn("domain",
    regexp_extract(col("description"), "\\*\\*Domain\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("context_summary",
    regexp_extract(col("description"), "###\\s*Context\\n+([^#\\n][^\\n]{0,200})", 1))
  .withColumn("output_description",
    regexp_extract(col("description"), "\\*\\*Output[:\\*]*\\s*([^\\n]{0,200})", 1))
  .withColumn("warp_pipe_product",
    regexp_extract(col("title"), "(?i)Add\\s+(.+?)\\s+(?:Activity|JM|Journey)", 1))
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("attribute_type"),
    col("owner_squad"),
    col("domain"),
    col("context_summary"),
    col("output_description"),
    col("warp_pipe_product"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

prContent.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_pr_content")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 7. Validation

// COMMAND ----------

// MAGIC %md
// MAGIC ### No joins in this pipeline
// MAGIC This analysis reads **only** `etl.ist__dataset.pull_request_events`. There are **no joins**. Duplicate and fan-out risk therefore does **not** come from join cardinality; it comes from **multiple source rows for the same PR** (same `repo_name` + `pr_number`). The checks below validate filters, grain, and aggregation safety under that model.

// COMMAND ----------

// DBTITLE 1,Check required columns after read
val requiredColumns = Seq(
  "action",
  "is_merged",
  "merged_at",
  "repo_name",
  "description",
  "title",
  "pr_number",
  "author",
  "added_lines",
  "deleted_lines",
  "changed_files",
  "created_at"
)
val missingAfterRead = requiredColumns.filterNot(allPRs.columns.contains)
require(
  missingAfterRead.isEmpty,
  s"Missing required columns on merged-closed slice: ${missingAfterRead.mkString(", ")}"
)

// COMMAND ----------

// DBTITLE 1,Validate date filter scope on merged_at
val mergedAtBoundsAll = allPRs.agg(
  min(col("merged_at")).alias("min_merged_at"),
  max(col("merged_at")).alias("max_merged_at")
).collect()(0)
println(
  s"[Validation] merged_at range after closed+merged+lower-bound filter: " +
    s"min=${mergedAtBoundsAll.getAs[Any]("min_merged_at")}, max=${mergedAtBoundsAll.getAs[Any]("max_merged_at")}"
)
// Lower bound is fixed in filters; min merged_at should be >= 2025-01-01 if data exists
val minTs = mergedAtBoundsAll.getAs[java.sql.Timestamp]("min_merged_at")
if (minTs != null) {
  require(
    !minTs.before(java.sql.Timestamp.valueOf("2025-01-01 00:00:00")),
    "merged_at min is before the configured lower bound 2025-01-01 — check date filter or data."
  )
}

// COMMAND ----------

// DBTITLE 1,Validate repo scope in classified PRs
val distinctRepos = aiPRs.select("repo_name").distinct().collect().map(_.getString(0)).sorted
println(s"[Validation] distinct repo_name in aiPRs: ${distinctRepos.mkString(", ")}")
val allowedRepos = Set("itaipu", "cross-segment-ai-tools")
val unexpected = distinctRepos.filterNot(allowedRepos.contains)
require(
  unexpected.isEmpty,
  s"Unexpected repo_name values in aiPRs (expected subset of itaipu, cross-segment-ai-tools): ${unexpected.mkString(", ")}"
)

// COMMAND ----------

// DBTITLE 1,Validate intended grain and duplicate PR rows
// Intended analytic grain for PR counts: one logical PR = (repo_name, pr_number)
val aiPrRowCount = aiPRs.count()
val distinctPrKeys = aiPRs.select("repo_name", "pr_number").distinct().count()
val distinctPrNumberOnly = aiPRs.select("pr_number").distinct().count()
println(s"[Validation] aiPRs row count: $aiPrRowCount")
println(s"[Validation] distinct (repo_name, pr_number): $distinctPrKeys")
println(s"[Validation] distinct pr_number only: $distinctPrNumberOnly")
require(
  aiPrRowCount == distinctPrKeys,
  s"Duplicate rows at PR grain (repo_name, pr_number): rows=$aiPrRowCount distinctKeys=$distinctPrKeys — sum() metrics may double-count; investigate source grain."
)
if (distinctPrNumberOnly < distinctPrKeys) {
  println("[Validation] WARN: same pr_number appears under more than one repo_name in scope (unusual); PR metrics use countDistinct(pr_number) — interpret cross-repo collisions carefully.")
}

// COMMAND ----------

// DBTITLE 1,Validate aggregation safety for monthly PR counts
// For each month, sum of total_prs across ai_tool should match distinct PRs merged in that month
val monthlyFromVolume = monthlyVolume
  .groupBy("month")
  .agg(sum("total_prs").alias("sum_prs_by_tool"))
val distinctByMonth = aiPRs
  .withColumn("month", date_trunc("month", col("merged_at")))
  .groupBy("month")
  .agg(countDistinct("pr_number").alias("distinct_prs_month"))
val monthlyRecon = monthlyFromVolume.join(distinctByMonth, Seq("month"), "full_outer")
  .withColumn("delta", col("sum_prs_by_tool") - col("distinct_prs_month"))
display(monthlyRecon.select("month", "sum_prs_by_tool", "distinct_prs_month", "delta"))
val reconOff = monthlyRecon.filter(
  col("sum_prs_by_tool").isNull ||
    col("distinct_prs_month").isNull ||
    col("delta").isNull ||
    col("delta") =!= lit(0)
).count()
require(reconOff == 0, "Monthly volume total_prs does not reconcile to countDistinct(pr_number) by month — check classification or duplicates.")

// COMMAND ----------

// DBTITLE 1,Validate sum metrics use same row set as PR grain
// If duplicate PR rows were present, line sums would inflate while countDistinct would not; covered by PR-key duplicate check above.
println("[Validation] Aggregation safety: PR cardinality uses countDistinct(pr_number); line/file sums use all aiPRs rows — safe only if one row per (repo_name, pr_number) (asserted above).")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 8. Display

// COMMAND ----------

// DBTITLE 1,Display monthly PR volume
display(monthlyVolume)

// COMMAND ----------

// DBTITLE 1,Display breakdown by author
display(byAuthor)

// COMMAND ----------

// DBTITLE 1,Display time to merge
display(timeToMerge)

// COMMAND ----------

// DBTITLE 1,Display PR list
display(prList)

// COMMAND ----------

// DBTITLE 1,Display outputs per PR
display(outputsPerPR)

// COMMAND ----------

// DBTITLE 1,Display monthly outputs
display(monthlyOutputs)

// COMMAND ----------

// DBTITLE 1,Display cumulative total
display(cumulativeTotal)

// COMMAND ----------

// DBTITLE 1,Display PR content breakdown
display(prContent)
