// Databricks notebook source
// MAGIC %md
// MAGIC # AI-Assisted PRs Monitor
// MAGIC
// MAGIC **Context**: This notebook supports monthly OKR reporting on AI-assisted pull request activity in engineering repositories.
// MAGIC
// MAGIC **Objective**: Measure merged PR volume, author activity, time-to-merge, estimated AI outputs, and PR content attributes for `itaipu` (Rapidash / Warp Pipe patterns) and `cross-segment-ai-tools`, based on a single source of truth in `pull_request_events`.
// MAGIC
// MAGIC **Method**:
// MAGIC 1. Read merged, closed PR events from `etl.ist__dataset.pull_request_events`.
// MAGIC 2. Apply repository and description/title filters to classify AI tooling (Rapidash, Warp Pipe, cross-segment-ai-tools).
// MAGIC 3. Build monthly and author-level aggregates using `countDistinct` on `pr_number` where applicable.
// MAGIC 4. Run validations on grain, duplicates, required columns, date scope, and repo filters (no joins in this pipeline).
// MAGIC 5. Materialize curated tables and display results.
// MAGIC
// MAGIC **Analysis structure**:
// MAGIC - 1. Imports
// MAGIC - 2. Data sources
// MAGIC - 3. Widgets
// MAGIC - 4. Variable filters
// MAGIC - 5. Functions
// MAGIC - 6. Code / analysis
// MAGIC - 7. Validation
// MAGIC - 8. Display
// MAGIC
// MAGIC **Data sources**:
// MAGIC - `etl.ist__dataset.pull_request_events` — event-level merged PR records; base for all metrics (user-confirmed sole dataset).
// MAGIC
// MAGIC **Main assumptions**:
// MAGIC - `merged_at >= '2025-01-01'` defines the reporting window for this notebook version.
// MAGIC - PR identity for deduplication is `(repo_name, pr_number)`; metrics use `countDistinct("pr_number")` within groups that include `repo_name` or single-repo slices — see validation for row-level duplicate risk on sums.
// MAGIC - This pipeline does not join other tables; correctness depends on filters and grain of the source table only.

// COMMAND ----------

// MAGIC %md
// MAGIC ## 1. Imports

// COMMAND ----------

// DBTITLE 1,Spark imports
import org.apache.spark.sql.DataFrame
import org.apache.spark.sql.functions._

// COMMAND ----------

// MAGIC %md
// MAGIC ## 2. Data sources

// COMMAND ----------

// DBTITLE 1,Load pull request events
// Dataset rationale: single base table for merged PR events; grain is event row (multiple rows per PR possible).
// Role: base. Key dimensions used: repo_name, pr_number, author, merged_at, description, title, line/file metrics, created_at.
val pullRequestEvents: DataFrame = spark.table("etl.ist__dataset.pull_request_events")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 3. Widgets

// COMMAND ----------

// MAGIC %md
// MAGIC No runtime widgets in this notebook; `merged_at` lower bound and repo filters are fixed in code as in the source analysis.

// COMMAND ----------

// MAGIC %md
// MAGIC ## 4. Variable filters

// COMMAND ----------

// DBTITLE 1,Filter merged closed PRs and reporting window
val mergedAtLowerBound = "2025-01-01"

val allPRs = pullRequestEvents
  .filter(col("action") === "closed")
  .filter(col("is_merged") === true)
  .filter(col("merged_at") >= mergedAtLowerBound)

// Rapidash: explicit signature "Generated by Rapidash" in the description
val rapidashFilter =
  col("repo_name") === "itaipu" &&
  col("description").like("%Generated by Rapidash%")

// Warp Pipe: PRs that effectively create products (JM + Activity + Eligibility + Conversion)
// Excludes infra/cleanup PRs that only mention Warp Pipe
val warpPipeFilter =
  col("repo_name") === "itaipu" && (
    col("description").like("%Warp Pipe%") ||
    col("description").like("%WarpPipe%")
  ) && (
    col("title").like("%w/ Warp Pipe%") ||
    col("description").like("%Config object%") ||
    col("description").like("%productCustomerStatus%")
  )

// DBTITLE 1,Classify AI-assisted PRs and tool label
val aiPRs = allPRs
  .filter(rapidashFilter || warpPipeFilter || col("repo_name") === "cross-segment-ai-tools")
  .withColumn("ai_tool",
    when(col("repo_name") === "cross-segment-ai-tools", lit("cross-segment-ai-tools"))
    .when(col("description").like("%Generated by Rapidash%"), lit("Rapidash"))
    .otherwise(lit("Warp Pipe"))
  )

// COMMAND ----------

// MAGIC %md
// MAGIC ## 5. Functions

// COMMAND ----------

// MAGIC %md
// MAGIC No shared helper functions; transformations are inlined in the analysis cells to preserve the original logic.

// COMMAND ----------

// MAGIC %md
// MAGIC ## 6. Code / analysis

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.1 Monthly PR volume

// COMMAND ----------

// DBTITLE 1,Aggregate monthly volume by AI tool
val monthlyVolume = aiPRs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    countDistinct("author").alias("unique_authors"),
    sum("added_lines").alias("total_lines_added"),
    sum("deleted_lines").alias("total_lines_deleted"),
    sum("changed_files").alias("total_files_changed")
  )
  .orderBy(col("month").desc, col("ai_tool"))

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.2 Breakdown by author and month

// COMMAND ----------

// DBTITLE 1,Aggregate PR metrics by author and month
val byAuthor = aiPRs
  .groupBy(
    date_trunc("month", col("merged_at")).alias("month"),
    col("ai_tool"),
    col("author")
  )
  .agg(
    countDistinct("pr_number").alias("prs_merged"),
    sum("added_lines").alias("lines_added"),
    sum("deleted_lines").alias("lines_deleted")
  )
  .orderBy(col("month").desc, col("prs_merged").desc)

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.3 Average time to merge (hours)

// COMMAND ----------

// DBTITLE 1,Compute hours to merge and monthly averages
val timeToMerge = aiPRs
  .withColumn("hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 1)
  )
  .groupBy(date_trunc("month", col("merged_at")).alias("month"), col("ai_tool"))
  .agg(
    round(avg("hours_to_merge"), 1).alias("avg_hours_to_merge"),
    min("hours_to_merge").alias("min_hours"),
    max("hours_to_merge").alias("max_hours"),
    countDistinct("pr_number").alias("total_prs")
  )
  .orderBy(col("month").desc, col("ai_tool"))

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.4 Individual PR list

// COMMAND ----------

// DBTITLE 1,Build ordered PR list projection
val prList = aiPRs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .withColumn("hours_to_merge",
    round((unix_timestamp(col("merged_at")) - unix_timestamp(col("created_at"))) / 3600, 0)
  )
  .select(
    col("month"),
    col("ai_tool"),
    col("repo_name"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("added_lines"),
    col("deleted_lines"),
    col("changed_files"),
    col("hours_to_merge"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.5 AI outputs per PR (estimated attributes)
// MAGIC
// MAGIC **Counting methodology:**
// MAGIC - New Rapidash PRs: counts occurrences of `**Type**:` in the description — each attribute has exactly one type declaration
// MAGIC - Update/migration PRs (no `**Type**:`): counts attribute bullets matching `- **PascalCaseName**`
// MAGIC - Fallback: `changed_files` as minimum estimate (1 file ≈ 1 output)
// MAGIC - `cross-segment-ai-tools` PRs: counted as 1 output per PR (tools/templates, not attributes)

// COMMAND ----------

// DBTITLE 1,Estimate outputs per PR from description heuristics
val typeCount = size(split(col("description"), "\\*\\*Type\\*\\*:")) - 1

val bulletCount = size(expr("filter(split(description, '\n'), x -> x rlike '^- \\\\*\\\\*[A-Z][a-zA-Z0-9]*\\\\*\\\\*')"))

val attributeCount = greatest(typeCount, bulletCount)

val withOutputs = aiPRs
  .withColumn("estimated_outputs",
    when(col("ai_tool") === "cross-segment-ai-tools", lit(1))
    .when(col("ai_tool") === "Warp Pipe", lit(1))
    .when(attributeCount > 0, attributeCount)
    .otherwise(greatest(lit(1), col("changed_files") - 2))
  )

val outputsPerPR = withOutputs
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.6 Total AI outputs per month

// COMMAND ----------

// DBTITLE 1,Aggregate estimated outputs by month
val monthlyOutputs = withOutputs
  .groupBy(date_trunc("month", col("merged_at")).alias("month"))
  .agg(
    countDistinct("pr_number").alias("total_prs"),
    sum("estimated_outputs").alias("total_outputs"),
    round(avg("estimated_outputs"), 1).alias("avg_outputs_per_pr"),
    countDistinct("author").alias("unique_authors")
  )
  .orderBy(col("month").desc)

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.7 Cumulative total of AI-generated outputs

// COMMAND ----------

// DBTITLE 1,Global cumulative outputs and PR counts
val cumulativeTotal = withOutputs
  .agg(
    sum("estimated_outputs").alias("total_outputs_to_date"),
    countDistinct("pr_number").alias("total_prs_to_date"),
    countDistinct("author").alias("unique_authors_to_date")
  )

// COMMAND ----------

// MAGIC %md
// MAGIC ### 6.8 PR content breakdown (extracted from description)
// MAGIC
// MAGIC Extracts structured fields from Rapidash PR descriptions for detailed reporting.

// COMMAND ----------

// DBTITLE 1,Extract content fields from descriptions and titles
val prContent = withOutputs
  // Rapidash standard fields
  .withColumn("attribute_type",
    regexp_extract(col("description"), "\\*\\*Type\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("owner_squad",
    regexp_extract(col("description"), "\\*\\*Owner\\*\\*:\\s*(?:Squad\\.)?([^\\n]+)", 1))
  .withColumn("domain",
    regexp_extract(col("description"), "\\*\\*Domain\\*\\*:\\s*([^\\n]+)", 1))
  .withColumn("context_summary",
    regexp_extract(col("description"), "###\\s*Context\\n+([^#\\n][^\\n]{0,200})", 1))
  .withColumn("output_description",
    regexp_extract(col("description"), "\\*\\*Output[:\\*]*\\s*([^\\n]{0,200})", 1))
  // Warp Pipe: extract product name from title (e.g. "Add X Activity, Eligibility... w/ Warp Pipe")
  .withColumn("warp_pipe_product",
    regexp_extract(col("title"), "(?i)Add\\s+(.+?)\\s+(?:Activity|JM|Journey)", 1))
  .withColumn("month", date_format(col("merged_at"), "yyyy-MM"))
  .select(
    col("month"),
    col("ai_tool"),
    col("pr_number"),
    col("author"),
    col("title"),
    col("attribute_type"),
    col("owner_squad"),
    col("domain"),
    col("context_summary"),
    col("output_description"),
    col("warp_pipe_product"),
    col("estimated_outputs"),
    col("merged_at")
  )
  .orderBy(col("merged_at").desc)

// COMMAND ----------

// MAGIC %md
// MAGIC ## 7. Validation

// COMMAND ----------

// MAGIC %md
// MAGIC ### 7.0 Joins
// MAGIC This notebook uses **no joins**: all metrics are derived from `etl.ist__dataset.pull_request_events` only. Validation therefore focuses on **source grain**, **filter semantics**, **deduplication of PRs**, and **aggregation safety** (row-level duplicates inflating `sum` aggregates).

// COMMAND ----------

// DBTITLE 1,Check required columns after read and filter
val requiredColumns = Seq(
  "action",
  "is_merged",
  "merged_at",
  "repo_name",
  "description",
  "title",
  "pr_number",
  "author",
  "added_lines",
  "deleted_lines",
  "changed_files",
  "created_at"
)
val availableColumns = pullRequestEvents.columns.toSet
val missingColumns = requiredColumns.filterNot(availableColumns.contains)
require(missingColumns.isEmpty, s"Missing required columns in source table: ${missingColumns.mkString(", ")}")

// COMMAND ----------

// DBTITLE 1,Validate merged_at date filter scope on aiPRs
val mergedAtBounds = aiPRs.agg(
  min("merged_at").alias("min_merged_at"),
  max("merged_at").alias("max_merged_at")
).collect()(0)
println(s"Date filter: merged_at >= $mergedAtLowerBound")
println(s"Actual min(merged_at) in aiPRs: ${mergedAtBounds.getAs[Any]("min_merged_at")}")
println(s"Actual max(merged_at) in aiPRs: ${mergedAtBounds.getAs[Any]("max_merged_at")}")

// COMMAND ----------

// DBTITLE 1,Validate repo distribution against intended filters
// Expected: only `itaipu` and `cross-segment-ai-tools` appear in aiPRs (Warp Pipe and Rapidash paths are itaipu-only).
val repoDistribution = aiPRs.groupBy("repo_name").count().orderBy(col("count").desc)
display(repoDistribution)

// COMMAND ----------

// DBTITLE 1,Validate intended grain and duplicate PR rows at repo PR grain
// Grain: each analytical PR is identified by (repo_name, pr_number). Multiple event rows per PR would inflate sum() on line/file metrics.
val prGrainDupes = aiPRs
  .groupBy("repo_name", "pr_number")
  .count()
  .filter(col("count") > 1)

val duplicatePrGroupCount = prGrainDupes.count()
println(s"Duplicate (repo_name, pr_number) groups with row count > 1: $duplicatePrGroupCount")
display(prGrainDupes.limit(100))

val totalRowsAiPRs = aiPRs.count()
val distinctPrKeys = aiPRs.select("repo_name", "pr_number").distinct().count()
println(s"aiPRs row count: $totalRowsAiPRs")
println(s"Distinct (repo_name, pr_number): $distinctPrKeys")
if (totalRowsAiPRs > distinctPrKeys) {
  println("WARNING: Row count exceeds distinct PR keys; sum(added_lines), sum(deleted_lines), sum(changed_files), and sum(estimated_outputs) may double-count unless each metric is defined per-event by design.")
}

// COMMAND ----------

// DBTITLE 1,Validate PR counting distinct vs naive count at monthly grain
// monthlyVolume uses countDistinct(pr_number) within (month, ai_tool) — safe if pr_number could repeat across months only as same PR in one month; validates magnitude vs raw count.
val monthlyVolumeSanity = aiPRs
  .withColumn("month", date_trunc("month", col("merged_at")))
  .groupBy("month", "ai_tool")
  .agg(
    count("*").alias("row_count"),
    count("pr_number").alias("count_pr_number"),
    countDistinct("pr_number").alias("distinct_pr_number")
  )
  .orderBy(col("month").desc, col("ai_tool"))
display(monthlyVolumeSanity)

// COMMAND ----------

// DBTITLE 1,Validate aggregation alignment for monthly volume totals
// Compare sum of monthly countDistinct total_prs across tools to global distinct PR count (approximate reconciliation; cross-check for large drift).
val sumMonthlyDistinctPrs = monthlyVolume.agg(sum("total_prs").alias("sum_monthly_bucket_distinct_prs")).collect()(0).getAs[Any]("sum_monthly_bucket_distinct_prs")
val globalDistinctPrs = aiPRs.select("repo_name", "pr_number").distinct().count()
println(s"Sum of monthly total_prs (countDistinct within month x ai_tool): $sumMonthlyDistinctPrs")
println(s"Global distinct (repo_name, pr_number) in aiPRs: $globalDistinctPrs")
println("Note: Sum of per-bucket countDistinct can exceed global distinct when the same PR appears in multiple ai_tool labels or spans buckets; here ai_tool is mutually exclusive per row, but a PR could only appear once per row set — interpret drift if any.")

// COMMAND ----------

// MAGIC %md
// MAGIC ## 8. Display

// COMMAND ----------

// DBTITLE 1,Write and display monthly volume
monthlyVolume.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_volume_mensal")
display(monthlyVolume)

// COMMAND ----------

// DBTITLE 1,Write and display author breakdown
byAuthor.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_por_autor")
display(byAuthor)

// COMMAND ----------

// DBTITLE 1,Write and display time to merge
timeToMerge.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_tempo_merge")
display(timeToMerge)

// COMMAND ----------

// DBTITLE 1,Write and display PR list
prList.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_lista_prs")
display(prList)

// COMMAND ----------

// DBTITLE 1,Write and display outputs per PR
outputsPerPR.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_por_pr")
display(outputsPerPR)

// COMMAND ----------

// DBTITLE 1,Display monthly outputs cumulative metrics
// monthlyOutputs.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_outputs_mensais")
display(monthlyOutputs)

// COMMAND ----------

// DBTITLE 1,Write and display cumulative totals
cumulativeTotal.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_total_acumulado")
display(cumulativeTotal)

// COMMAND ----------

// DBTITLE 1,Write and display PR content breakdown
prContent.write.format("delta").mode("overwrite").option("overwriteSchema", "true").saveAsTable("usr.br__customer_lifecycle_optimization.ai_monitor_pr_content")
display(prContent)
